### ISSUE TITLE
[Bug] Dashboard data is loading extremely slow on PostgreSQL

### ISSUE THREAD

**Issue by bazenkov** [thingsboard/thingsboard#4519] opened 2021-04-29 13:07 UTC
**Describe the bug**
I have dashboard with a device list and a single timeseries chart. When I retrieve data for the last 30 days the data loads in 6-8 minutes. Sometimes the device list also loads extremely slow. In PgAdmin I see the following queries:
`select tskventity0_.entity_id as entity_i1_24_, tskventity0_.key as key2_24_, tskventity0_.ts as ts3_24_, tskventity0_.bool_v as bool_v4_24_, tskventity0_.dbl_v as dbl_v5_24_, tskventity0_.json_v as json_v6_24_, tskventity0_.long_v as long_v7_24_, tskventity0_.str_v as str_v8_24_ from ts_kv AS tskventity0_ where tskventity0_.entity_id=$1 and tskventity0_.key=$2 and tskventity0_.ts>=$3 and tskventity0_.ts<$4 order by tskventity0_.ts desc nulls last limit $5`

When I run this query from PgAdmin console for some entity_id, key and ts limits for the last 30 days the query takes less than 5 seconds to finish. CPU and memory loads are less than 50%. So, it seems the problem is not in the PostgreSQL settings or hardware.
There are no errors in thingsboard.log

**Your Server Environment**
Local infrastructure: 8 CPU, 32 GB RAM
Thingsboard 3.2.1 
PostgreSQL 12
openSUSE Leap 15.2. The problem also occurs on Ubuntu 18.10

**Your Client Environment**
* Windows 10 x64
* Mozilla Firefox 
* 87.0

**To Reproduce**
1. Create a dashboard with the entity list and a single timeseries chart
2. Select a device in the entity list
3. Select the telemetry for the last 30 days
4. The data is loading very slow (>=5 minutes)

**Expected behavior**
The data should loads in 5-10 seconds.

**Screenshots**
![2021-04-29_16-08-44](https://user-images.githubusercontent.com/11899310/116555534-2f64d500-a905-11eb-9188-a328de7f8bc5.png)

**Additional context**
Current estimated rowcount of ts_kv tables is ~ 2 billions
[tb_logs.zip](https://github.com/thingsboard/thingsboard/files/6398739/tb_logs.zip)

**Comment by Alentus** [comment] 2021-05-28 05:46
@bazenkov Hello, you have found the solution? I have a same problem.

**Comment by bazenkov** [comment] 2021-06-03 18:23
> @bazenkov Hello, you have found the solution? I have a same problem.

I added to the thingsboard.conf the line:
export TB_SERVER_WS_SEND_TIMEOUT=60000

The hanging behavior seems to disappear. It may be possible the thingsboard was spamming database with requests when didn't received the response during the timeout.

**Comment by Wanderzhd** [comment] 2021-06-08 06:48
We have the same problem here and changing the TB_SERVER_WS_SEND_TIMEOUT would not help.

**Comment by limejeroen** [comment] 2021-07-16 09:27
I have exactly the same problem and I have found a solution that works for me.

The problem is in the "desc nulls last" part of the query. The primary key index is built with "desc nulls first" AKA "asc nulls last" (the default). Therefore it cannot use the index for your query!

I worked around it by creating another index, identical to the primary key index but with DESC NULLS LAST on the ts column.

`CREATE UNIQUE INDEX ts_kv_entity_id_idx ON public.ts_kv (entity_id,"key",ts desc nulls last);`

Can this be fixed in Thingsboard application code @ashvayka @vvlladd28? I think the "desc nulls last" query makes no sense since it is a non-NULL column anyway. Right now it seems Dashboards simply do not work with big tables (mine was 26 GB). FYI using pure postgres, no Cassandra or TimescaleDB. TB CE 3.2.1 (upgraded all the way from 3.0.1).

**Comment by smatvienko-tb** [comment] 2021-07-21 08:56
@limejeroen 
The parameter in thingsboard.yml that is responsible for NULLS LAST is
`spring.jpa.properties.hibernate.order_by.default_null_ordering: "last"`
https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/appendices/Configurations.html
Try to switch to "none" value. 
`spring.jpa.properties.hibernate.order_by.default_null_ordering: "none"`
That will remove explicit NULLS LAST from SQL queries and will use database-specific nulls order

**Comment by limejeroen** [comment] 2021-07-26 12:07
@smatvienko-tb that is very helpful, thanks!
Shouldn't this be the default setting?

**Comment by smatvienko-tb** [comment] 2021-07-26 13:53
> @smatvienko-tb that is very helpful, thanks!
> Shouldn't this be the default setting?

@limejeroen That is a goal, but some UI features can relay on DESC NULLS LAST order, and that is not easy to test the entire project UI instantly. So it will remain for a while until we ensure that it's not breaking the things.

**Comment by bazenkov** [comment] 2021-09-17 10:22
I've tried to set 
`spring.jpa.properties.hibernate.order_by.default_null_ordering: "none"`
But after TB was restarted, the active queries still have DESC NULLS LAST
Then I explicitly set 
`spring.jpa.properties.hibernate.order_by.default_null_ordering: "first"`
Now when trying to load telemetry in a dashboard I can see two identical SELECT queries, one with DESC NULLS FIRST and one with DESC NULLS LAST.
See the screenshot
![image](https://user-images.githubusercontent.com/11899310/133767627-b0467777-d8c7-42f5-bb54-425ce941c3d2.png)

The data loading time is still

**Closed** 2024-03-17 12:00 UTC
Labels: bug
