### ISSUE TITLE
How to select device profile when provisioning with thingsboard-gateway?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3868] opened 2020-12-19 06:27 UTC
Hello

I have thingsboard gateway with mqtt connector.

It is listening to topic /devices/deviceType/incoming

assuming I have different device types, deviceType1 and deviceType2

When device is sending message for the first time, how I can control which DEVICE PROFILE it is created under?

I would like to have profile1 for deviceType1 and profile2 for deviceType2

when device sends message for the first time, it will be created with the required device profile

There is no Set Device Profile node in the rule chain 

I don't see thingsboard gateway field for it, is it just deviceType now?

How can this be done?

thanks

Kindly

**Comment by t0mmyz7** [comment] 2020-12-20 08:23
so is there a way to do deviceProvisioning when device is first created?

https://thingsboard.io/docs/user-guide/device-provisioning/?mqttprovisioning=without#mqtt-device-apis

i am using mqtt connector in tb-gateway.

**Comment by zbeacon** [comment] 2020-12-22 06:37
Hi @t0mmyz7 ,

Thank you for your interest in ThingsBoard IoT gateway.
At this moment device profile name works like device type in older versions. We did it to keep backward compatibility. So if your device has deviceType1 as deviceType in the gateway and you have device profile with the same name in ThingsBoard, it will be assigned to device. If you don't have device profile with such name, it will be created with configuration like in default device profile.

The gateway doesn't support deviceProvisioning feature, because of it was designed to create device at very beginning. We are not going to change this part of the gateway logic at the moment, but maybe we will add functionality like in pre-provisioned strategy (Disallow to create devices by the gateway and allow only data sending to existing devices).

**Closed** 2021-01-12 08:45 UTC
Labels: question

**Comment by pnavazzotti** [comment] 2021-09-23 16:08
Hello,

I have the same problem with ThingsBoard IoT gateway. I cannot configure "DeviceTypeJsonExpression" field in mqtt.json file. As show in the image, I tried to pass it a device type value different that the default one.
` "mapping":[
      {
         "topicFilter": "dig_ronda",
         "converter":{
            "type": "json",
            "filterExpression": "$",
            "deviceNameJsonExpression": "rondas",
            "deviceTypeJsonExpression": "Rondas",
            "attributes":[
            ],`
The problem is that in Thingsboard the device is generated with the default profile.
![image](https://user-images.githubusercontent.com/82518618/134542642-f85688c3-11cf-4262-a4f0-f9a9618202ab.png)

Previously, I generate the device profile "Rondas"

I am using tb-gateway 2.2

Thanks.

**Comment by t0mmyz7** [comment] 2021-09-23 18:36
Hi 
at the end this was working fine for us
we set it up like so:
```
    "mapping": [
        {
            "topicFilter": "/thingsboard/sensors/temp1",
            "converter": {
                "type": "json",
                "deviceNameJsonExpression": "${deviceId}",
                "deviceTypeJsonExpression": "${model}",
                "timeout": 1200,
                "attributes": [
                    {
                        "type": "string",
                        "key": "model",
                        "v
```


we use "model": "xxx123" from the incoming payload to set the deviceType (Profile). If we had this profile created in TB, the device was created under it.

not sure what was

**Comment by pnavazzotti** [comment] 2021-09-23 19:52
Hello @t0mmyz7 , this is very similar as to what we have, but instead of evaluating the deviceNameJsonExpression and Type with JsonPath we want to hardcore these values as strings, and this is where the problem shows up. We hardcore these values as we only expect this one device to send messages to this topic.
Of course, we have created beforehand a device profile called Rondas, with the Transport configuration set to MQTT and listening in the topic dig_ronda. We've also tried to set the Device Provisioning tab to "Allow to create new devices"/default and it doesn't work.
Any ideas?
   ```
 "mapping": [
        {
            "topicFilter": "dig_ronda",
            "converter": {
                "type": "json",
                "deviceNameJsonExpression": "rondas",
                "deviceTypeJsonExpression": "Rondas",
                "timeout": 1200,
                "attributes": [
                    {
                        "type": "string",
                        "key": "model",
                        "v
```
