### ISSUE TITLE
[Bug, Feature Request] Lost work when concurrently editing a dashboard

### ISSUE THREAD

**Issue by pavelkomarov** [thingsboard/thingsboard#5540] opened 2021-11-12 00:07 UTC
If I edit a dashboard at the same time as someone else, make changes, and save, and then they save, their changes completely delete my work.

Thingsboard v3.3.1, hosted by my company.

Mac, Big Sur, Chrome v95.0.4638.69, connecting via http

1. Edit a board
2. Observe your hard work vanish later for some mysterious reason
3. Find out it was just because someone else had it open in edit mode oops

Expected behavior:
Don't commit a nothing change that deletes a bunch of content.

**Comment by JacksonBowe** [comment] 2021-11-12 01:26
As annoying as this is, it's not a bug.

Possibly a feature request.

**Comment by pavelkomarov** [comment] 2021-11-12 17:07
I think it's bug-like. Easy fix until we can solve the hard, sophisticated problem of showing people others' edits live or of merging changes together: Just show me when someone else is editing and lock the page.

As is, my team is having to literally create new boards for every change, so we don't risk stepping on each other. It's completely unsustainable and confusing.

**Comment by trikimiki** [comment] 2022-02-09 14:37
Feature request #6033 is in the development team's backlog; Git support for dashboards should solve this kind of issue.

**Comment by Ultrazombie** [comment] 2022-02-10 09:30
@pavelkomarov 
I will close this issue as there is already such a feature request and will be introduced soon

**Closed by Ultrazombie** 2022-02-10 09:30 UTC
Labels: bug
