### ISSUE TITLE
can't start thingsboard 2.1.1 / 2.1.2

### ISSUE THREAD

**Issue by msalajka** [thingsboard/thingsboard#1147] opened 2018-10-12 13:26 UTC
hello,

i've installed version 2.1. when i tried to update to 2.1.1 or 2.1.2, it fails ...

**OS:**
Linux test 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**JAVA:**
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

[root@test thingsboard]# **cat thingsboard.log | grep ERROR**
2018-10-12 14:52:49,840 [localhost-startStop-1] ERROR o.s.b.c.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#4f6a348a' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#4f6a348a': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
2018-10-12 14:52:49,932 [main] ERROR o.s.boot.SpringApplication - Application startup failed

**rollback to 2.1.0**
yum downgrade thingsboard-2.1.0.rpm
**OK**

**Comment by cristianhumelnicu** [comment] 2018-10-19 05:54
Hi ,

I still can not start Thingsboard 2.1.1, 2,1,2 or 2.13.

When i start TB service probram stuck

at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
        ... 16 common frames omitted

I can not figure out how to solve this . Any helping ideea ?

**Comment by vparomskiy** [comment] 2018-10-19 06:31
Please provide a full log file, because your log does not include root cause of the problem.

**Comment by cristianhumelnicu** [comment] 2018-10-19 06:51
@vparomskiy , sure .. there it is:

gw@gateway:~ $ tail -f /var/log/thingsboard/thingsboard.log
2018-10-19 09:47:22,432 [Thread-7] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebAp                                                                             plicationContext - Closing org.springframework.boot.context.embedded.AnnotationC                                                                             onfigEmbeddedWebApplicationContext@a94ee4: startup date [Fri Oct 19 09:02:31 EES                                                                             T 2018]; root of context hierarchy
2018-10-19 09:47:22,460 [Thread-7] INFO  o.s.c.s.DefaultLifecycleProcessor - Sto                                                                             pping beans in phase 2147483647
2018-10-19 09:47:22,504 [Thread-7] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unr                                                                             egistering JMX-exposed beans on shutdown
2018-10-19 09:47:22,516 [Thread-7] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutt                                                                             ing down ExecutorService 'defaultSockJsTaskScheduler'
2018-10-19 09:47:22,535 [Thread-7] INFO  o.t.s.t.mqtt.MqttTransportService - Sto                                                                             pping MQTT transport!
2018-10-19 09:47:22,581 [Thread-7] INFO  o.t.s.t.mqtt.MqttTransportService - MQT                                                                             T transport stopped!
2018-10-19 09:47:23,333 [Thread-7] INFO  o.t.s.a.service.DefaultActorService - A                                                                             ctor system terminated: Terminated(Actor[akka://Akka/])
2018-10-19 09:47:23,365 [Thread-7] INFO  o.t.s.s.c.rpc.ClusterGrpcService - Goin                                                                             g to onStop RPC server
2018-10-19 09:47:23,398 [Thread-7] INFO  o.t.s.s.c.rpc.ClusterGrpcService - RPC                                                                              server stopped!
2018-10-19 09:47:23,433 [Thread-7] INFO  o.s.o.j.LocalContainerEntityManagerFact                                                                             oryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2018-10-19 09:49:15,766 [main] INFO  o.t.s.ThingsboardServerApplication - Starting ThingsboardServerApplication v2.1.3 on gateway with PID 2522 (/usr/share/thingsboard/bin/thingsboard.jar started by thingsboard in /usr/share/thingsboard/bin)
2018-10-19 09:49:15,797 [main] INFO  o.t.s.ThingsboardServerApplication - No active profile set, falling back to default profiles: default
2018-10-19 09:49:16,309 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a94ee4: startup date [Fri Oct 19 09:49:16 EEST 2018]; root of context hierarchy
2018-10-19 09:49:16,573 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
2018-10-19 09:49:32,006 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [class org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$4fe6cbc3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:32,112 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cache.annotation.ProxyCachingConfiguration' of type [class org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$4b39a7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:32,847 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'objectPostProcessor' of type [class org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:32,865 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@13d101b' of type [class org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:32,972 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [class org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$74bb6e75] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:33,130 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'methodSecurityMetadataSource' of type [class org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-10-19 09:49:33,593 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
2018-10-19 09:49:33,812 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
        ... 16 common frames omitted

If i revert back to 2.1 works ...

Thx!

**Comment by vparomskiy** [comment] 2018-10-19 07:33
Please write were did you get tb 2.1.3 package (download link or branch name if build from sources)
And OS (name/version)

**Comment by cristianhumelnicu** [comment] 2018-10-19 08:15
> Please write were did you get tb 2.1.3 package (download link or branch name if build from sources)
> And OS (name/version)

https://github.com/thingsboard/thingsboard/releases/download/v2.1.3/thingsboard-2.1.3.deb

Rapbian on RPI3B

gw@gateway:~ $ uname -r
4.14.71-v7+

**Comment by msalajka** [comment] 2018-10-19 08:47
# /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0
 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Starting ThingsBoard Upgrade from version 2.0.0 ...
Upgrading ThingsBoard from version 2.0.0 to 2.1.1 ...
Updating schema ...
Schema updated.
Upgrading ThingsBoard from version 2.1.1 to 2.1.2 ...
Dumping entity views ...
Entity views dumped.
Updating schema ...
Schema updated.
Restoring entity views ...
Entity views restored.
Updating system data...
Upgrade finished successfully!
ThingsBoard upgraded successfully!

**Comment by cristianhumelnicu** [comment] 2018-10-19 09:12
@vparomskiy 

gw@gateway:~ $ sudo systemctl stop thingsboard.service
[sudo] password for gw:
gw@gateway:~ $ sudo dpkg -i thingsboard-2.1.3.deb
(Reading database ... 116539 files and directories currently installed.)
Preparing to unpack thingsboard-2.1.3.deb ...
Unpacking thingsboard (2.1.3-1) over (2.1.0-1) ...
Setting up thingsboard (2.1.3-1) ...

Configuration file '/usr/share/thingsboard/conf/thingsboard.yml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** thingsboard.yml (Y/I/N/O/D/Z) [default=N] ? n
Processing triggers for systemd (232-25+deb9u4) ...
gw@gateway:~ $ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0

 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
ThingsBoard upgrade failed!

**Comment by vparomskiy** [comment] 2018-10-19 09:44
Please send your thingsboard.yml file.
I think that properties file was not merged correctly during package update

**Comment by cristianhumelnicu** [comment] 2018-10-19 11:10
@vparomskiy  Problem solved! Indeed was from YML ... 

Thx for support !

**Comment by cristianhumelnicu** [comment] 2018-10-19 11:14
So if @msalajka agree ... we can close the issue

**Comment by msalajka** [comment] 2018-10-19 12:39
please update https://thingsboard.io/docs/user-guide/install/upgrade-instructions/
for 2.1.1/2.1.2 and close ticket.
thanks
m.

**Closed as completed** 2018-12-04 15:27 UTC
