### ISSUE TITLE
[3.7] Profile OTA update fail to update devices shared attributes

### ISSUE THREAD

**Issue by FelixKikleo** [thingsboard/thingsboard#11443] opened 2024-08-19 13:37 UTC
Since upgrading 3.5.1 to 3.7, we have the same issue. Devices shared attributes don't update when changing the assigned OTA (framework or software) in the Profile. But if change the profile of the device, changes are made accordingly in the device shared attributes. 

Anyone working on this ? We have many devices, doing this manually for each device would be too time consuming

_Originally posted by @FelixKikleo in https://github.com/thingsboard/thingsboard/issues/6008#issuecomment-2296577451_

**Comment by mykhailokornieiev** [comment] 2024-08-19 15:11
Hi. I was unable to reproduce such behavior on 3.7. 
I've made the next: 
1. Created new OTA Firmware
2. Assigned it to device profile (not device)
As for device emulation I've used [http_firmware_client.py](https://thingsboard.io/docs/user-guide/resources/firmware/http_firmware_client.py)
![image](https://github.com/user-attachments/assets/5579ebdb-525c-419d-aa85-3138c8ac5d99)
![image](https://github.com/user-attachments/assets/47fe0fc2-8d92-44df-9ad9-181bf37d9c80)
I was able to reproduce similar behavior only when there was no device connected (it was stuck on fw_state = INITIATED)

Please provide full steps to reproduce your issue

**Comment by FelixKikleo** [comment] 2024-08-19 15:48
Hello, thanks for the quick answer. 

We are using community edition.

Steps to reproduce the issue:

1. Create a new profile
2. Assign a device to this profile
3. Create an OTA package for this profile
4. Assign this OTA package to the profile -> **no changes in shared_attributes of the device** (dc_ or fw_) and no message warning us that those changes may affect 1 device (we had this message in previous version)
5. Switch the device to another profile then switch it back to this new profile -> We can see changes in device shared attributes (version, tag, checksum,...)

**Comment by mykhailokornieiev** [comment] 2024-08-20 12:59
Hi. Thank you for the detailed steps to reproduce. I was able to reproduce this issue on CE. 
This looks like a bug in a platform - I had already added to our backlog a ticket for a product team.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Closed by mykhailokornieiev** 2024-08-20 12:59 UTC

**Comment by FelixKikleo** [comment] 2024-08-20 13:47
Thanks you. Any estimated date for the next release ? We can't really push updates while the bug is here.

**Comment by mykhailokornieiev** [comment] 2024-08-21 10:44
Hi. We plan to provide a fix for this bug in the next release, but we do not guarantee that it will be included. There is no estimated timeframe for the next release

**Comment by FelixKikleo** [comment] 2024-08-21 14:00
Ok thank you. By chance, do you know any way to circumvent this bug in the meantime (by creating an explicit rule for example) ?

**Comment by Nepherhotep** [comment] 2024-09-26 21:31
Looks like a major issue to me.
