### ISSUE TITLE
Accessing dashboard with JWT Token 

### ISSUE THREAD

**Issue by Codebreaker101** [thingsboard/thingsboard#911] opened 2018-07-04 08:18 UTC
I made an application that sits on top of ThingsBoard. It's using Thingsboard Auth API to authenticate user and authenticate API queries with the received token. Now I wish to add a link to ThingsBoard to access the dashboard for the devices from my application, but I don't want to authenticate again by entering username and password since I have already done that through the API. 

Is that possible with the current state of the application? Could that be a feature in a future release?

**Comment by mohan-mu** [comment] 2018-08-04 11:01
#942

**Comment by mohan-mu** [comment] 2018-08-04 11:01
Duplicate of #942

**Comment by mohan-mu** [comment] 2018-08-04 11:02
@Codebreaker101  Any solutions so far ?

**Comment by robertoenr** [comment] 2021-01-29 16:58
+1 Any solutions in recent versions?

**Comment by volodymyr-babak** [comment] 2022-02-09 07:58
You can add _X-Authorization_ header to the request headers:

**--header "X-Authorization: Bearer YOUR_JWT_TOKEN"**

This should allow accessing restricted dashboards (and other entities) without entering login and password.

**Closed** 2022-02-09 09:03 UTC
