### ISSUE TITLE
io.grpc.netty.NettyServerTransport - Transport failed

### ISSUE THREAD

**Issue by zgjbatyz** [thingsboard/thingsboard#710] opened 2018-04-09 08:25 UTC
2018-04-09 14:54:21,562 [grpc-default-worker-ELG-3-2] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,591 [grpc-default-worker-ELG-3-3] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,618 [grpc-default-worker-ELG-3-4] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,666 [grpc-default-worker-ELG-3-2] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,712 [grpc-default-worker-ELG-3-1] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,787 [grpc-default-worker-ELG-3-3] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:54:21,884 [grpc-default-worker-ELG-3-4] ERROR io.grpc.netty.NettyServerTransport - Transport failed
2018-04-09 14:55:12,470 [grpc-default-worker-ELG-3-1] ERROR io.grpc.netty.NettyServerTransport - Transport failed

**Comment by mp-loki** [comment] 2018-04-09 13:42
any more input on this? The errors you provide do not tell much

**Comment by zgjbatyz** [comment] 2018-04-11 09:18
2018-04-11 04:57:34,715 [grpc-default-worker-ELG-3-4] ERROR io.grpc.netty.NettyServerTransport - Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 47455420687474703a2f2f7777772e62616964752e636f6d
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:270)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:211)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vparomskiy** [comment] 2018-04-11 09:26
Provided hex decodes to String 
> GET http://www.baidu.com
This payload looks like HTTP/1.1 but grpc use HTTP/2

Could you please add more details?
1. How those errors reproduced on your system? 
2. Do you have any proxy?
3. How was Thingsboard is installed?
4. Why does Thingsboard receive GET request for another domain (http://www.baidu.com)?

**Comment by zgjbatyz** [comment] 2018-04-12 00:48
var mqtt = require('mqtt');

// Don't forget to update accessToken constant with your device access token
const thingsboardHost = "*.*.*.*";
const accessToken = "57pt5fSbciX*******";
const minTemperature = 17.5, maxTemperature = 42.5, minHumidity = 12, maxHumidity = 90;

// Initialization of temperature and humidity data with random values
var data = {
    temperature: minTemperature + (maxTemperature - minTemperature) * Math.random() ,
    humidity: minHumidity + (maxHumidity - minHumidity) * Math.random(),
    createTime:""
};

// Initialization of mqtt client using Thingsboard host and device access token
console.log('Connecting to: %s using access token: %s', thingsboardHost, accessToken);
var client  = mqtt.connect('mqtt://'+ thingsboardHost, { username: accessToken });

// Triggers when client is successfully connected to the Thingsboard server
client.on('connect', function () {
    console.log('Client connected!');
    // Uploads firmware version and serial number as device attributes using 'v1/devices/me/attributes' MQTT topic
    client.publish('v1/devices/me/attributes', JSON.stringify({"firmware_version":"1.0.1", "serial_number":"SN-001"}));
    // Schedules telemetry data upload once per second
    console.log('Uploading temperature and humidity data once per second...');
    setInterval(publishTelemetry, 2000);
});

// Uploads telemetry data using 'v1/devices/me/telemetry' MQTT topic
function publishTelemetry() {
    data.temperature = genNextValue(data.temperature, minTemperature, maxTemperature);
    data.humidity = genNextValue(data.humidity, minHumidity, maxHumidity);
    data.createTime=new Date().getTime();
    client.publish('v1/devices/me/telemetry', JSON.stringify(data));
}

// Generates new random value that is within 3% range from previous value
function genNextValue(prevValue, min, max) {
    var value = prevValue + ((max - min) * (Math.random() - 0.5)) * 0.03;
    value = Math.max(min, Math.min(max, value));
    return Math.round(value * 10) / 10;
}

//Catches ctrl+c event
process.on('SIGINT', function () {
    console.log();
    console.log('Disconnecting...');
    client.end();
    console.log('Exited!');
    process.exit(2);
});

//Catches uncaught exceptions
process.on('uncaughtException', function(e) {
    console.log('Uncaught Exception...');
    console.log(e.stack);
    process.exit(99);
});
——————————————————————————————————————————————

Connecting to: 120.24.*.* using access token: kwxDijEjFK9l8******
Client connected!
Uploading temperature and humidity data once per second...
Uncaught Exception...
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/opt/node_modules/mqtt/lib/client.js:893:15)
    at MqttClient._handlePacket (/opt/node_modules/mqtt/lib/client.js:329:12)
    at work (/opt/node_modules/mqtt/lib/client.js:271:12)
    at Writable.writable._write (/opt/node_modules/mqtt/lib/client.js:281:5)
    at doWrite (/opt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/opt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
Connecting to: 120.24.255.143 using access token: 57pt5fSbciXq6bfgBlp2
Client connected!
Uploading temperature and humidity data once per second...
Connecting to: 120.24.*.* using access token: 57pt5fSb********
Client connected!
Uploading temperature and humidity data once per second...

**Comment by zgjbatyz** [comment] 2018-04-12 00:51
nodejs version v6.14.1
use postgres

**Comment by zgjbatyz** [comment] 2018-04-12 01:02
os of thingsboard： CentOS 7.0 64
mqtt client： CentOS 7.0 64

thx

**Comment by sunqb** [comment] 2018-08-02 08:50
i have a same  problem

**Comment by sunqb** [comment] 2018-08-10 02:54
i have solved this problem。codec error

**Comment by rogercm** [comment] 2018-09-26 14:23
Hey sunqb! How did you solve this codec problem, please? Looks like I'm with same problem.

**Comment by ashvayka** [comment] 2020-06-02 12:12
I have tested latest setup on CentOS8 and don't see this issue not more. Probably fixed by upgrading netty dependency.

**Closed by ashvayka** 2020-06-02 12:12 UTC
