### ISSUE TITLE
[Bug] You can't save time series on device with API call if you have previously deleted timeseries with the same keys

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6844] opened 2022-06-28 13:22 UTC
**Describe the bug**
As described in [this issue](https://github.com/thingsboard/thingsboard/issues/6835) :
You can't save time series on device with API call if you have previously deleted timeseries with the same keys, if it is in a month older than the current month.

  * thingsboard.cloud

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser chrome
* Connectivity
  * HTTP

**To Reproduce**
1. Use the saveEntityTelemetry from the Swagger API and save a telemetry for a device in the previous month (i.e. in May if we currently are in June)
2. Use the deleteEntityTimeSeries for the same device with a time stamp range containing the previous save.
3.  Try to re-use the same saveEntityTelemetry from the Swagger API and save a telemetry for the same device for the same timestamp as before and with the same telemetry keys as in step 1).
4. See that the keys that should have been injected are not present for the timestamp in step 3) when you use getTimeSeries in the Swagger API with correct start and end timestamp containing the ts in step 3).

**Expected behavior**
Data should have been injected.

**Additional context**
If you provide a "new" key that have not previously been deleted, the key is correctly injected. 
If you provide a key that have been previously deleted, but for a ts in the current month, the key is correctly injected.

**Comment by mde2017** [comment] 2022-06-28 13:33
Hi @lucasKapf,

are you using Cassandra?
There is a similar issue mentioned here: https://github.com/thingsboard/thingsboard/issues/5660

**Comment by lucasKapf** [comment] 2022-06-28 13:49
Hi @mde2017, thank you for your answer. I don't know if i'm using Cassandra, I am using thingsboard cloud version. Do you know if it uses Cassandra ?

**Comment by lucasKapf** [comment] 2022-06-28 13:55
@mde2017 The issue that you mentioned is similar to mine, but not exactly the same : 
the reinjected data doesnt appear for me when using the getTimeSeries in the swagger API.

**Comment by sumin-denys** [comment] 2024-12-10 18:08
Hi @lucasKapf,

I couldn't reproduce the error you mentioned in the description of this issue. I assume that this error was resolved in one of our previous releases. So, I recommend you upgrade to the latest ThingsBoard version and try to reproduce this issue. 

In case you can reproduce this issue on versions 3.8.0 and higher or do not want to upgrade to newer versions of ThingsBoard, for further investigation of the cause of this issue, we need the following information:
- ThingsBoard version (instance version on which you got this error)
- Payload examples (json message that you send to the ThingsBoard via **saveEntityTelemetry**)

___
Tested setup:
- **Device**: mydev
- **Connection type**: HTTP
- **Device profile**: default
- **Tested months**: December 2024 and November 2024
- **ThingsBoard version**: 3.8.1

Python code for testing purposes:
```
import requests
import datetime

# Replace with your ThingsBoard URL and device access token
THINGSBOARD_URL = "http://thingsboard_url"
DEVICE_TOKEN = "device_access_token"

# Function to post telemetry data
def send_telemetry(token, telemetry_data):
    url = f"{THINGSBOARD_URL}/api/v1/{token}/telemetry"
    headers = {
        "Content-Type": "application/json"
    }
    response = requests.post(url, json=telemetry_data, headers=headers)
    if response.status_code == 200:
        print("Data sent successfully:", telemetry_data)
    else:
        print("Failed to send data:", response.status_code, response.text)

# Generate data for each day
for day in range(1, 31, +1):  # (30, 0, -1)
    # Create a datetime object for the specific day
    date = datetime.datetime(2024, 11, day)
    
    # Create telemetry data payload
    telemetry_data = {
        "ts": int(date.timestamp() * 1000),  # Timestamp in milliseconds
        "values": {
            "temperature": F'{day}',  # Example key-value pair
        }
    }
    
    # Send the telemetry data
    send_telemetry(DEVICE_TOKEN, telemetry_data)
```
**First API request**:
![image](https://github.com/user-attachments/assets/b60b6d95-146d-48de-b2fb-8842e67eb3b3)
**Second API request**:
![image](https://github.com/user-attachments/assets/c4df76ad-a626-4f26-915a-2c9669740f20)

**Comment by sumin-denys** [comment] 2024-12-30 15:59
Hi @lucasKapf,

Since there hasn’t been any activity, I’m closing this ticket for now. 
If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.

> Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).

**Closed** 2024-12-30 15:59 UTC
Labels: bug
