### ISSUE TITLE
[Bug] Timeseries mixed up in chart

### ISSUE THREAD

**Issue by Kater--S** [thingsboard/thingsboard#2933] opened 2020-06-10 10:25 UTC
After defining a chart, different timeseries' parameters are mixed up, e.g. the unit suffix (aka "special symbol to show next to value") and the displayed accuracy ("number of digits after floating point"). Applies to Y axis as well as to legend. Even after deleting a timeseries from the chart its settings are still used for other timeseries.

When using the chart, enabling/disabling timeseries will produce unreasonable scaling to different Y axes.

Own CE setup with ThingsBoard 3.0 in a Docker container under hosted Linux.
Desktop with macOS 10.14.6 + latest Safari browser

**Comment by MrZANE42** [comment] 2020-07-07 09:27
Pop-up seems ok though.
Here is a picture how it look on one of our graphs (Pop-Up is correct)
![Graph bug](https://user-images.githubusercontent.com/7534100/86758958-803cd180-c044-11ea-8932-c05b79d2e322.png)

**Comment by MrZANE42** [comment] 2020-08-13 15:56
Is this fixed in 3.1PE? 
It's very annoying and should be easy to fix

**Comment by sumin-denys** [comment] 2024-11-15 17:39
Hi @MrZANE42,

Could you please share more details about this issue and include the steps to reproduce it? I would greatly appreciate your input.

**Comment by sumin-denys** [comment] 2024-12-09 18:30
Hi @MrZANE42,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.

**Closed by sumin-denys** 2024-12-09 18:30 UTC
Labels: bug
