### ISSUE TITLE
[Bug] Data is processed multiple in Rulechain for Kubernetes Deployment with Kafka Queue

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#4628] opened 2021-05-26 13:30 UTC
**Describe the bug**
In our Kubernetes Cluster Deployment with Kafka Backend Consumer Groups were spawned multiple time for each Cluster Node. This leads to data being twice in the TB rulechains affecting Alarms and data processing in general.

**Your Server Environment**
- ThingsBoard 3.2.2 PE
- Azure Cloud
- Kubernetes 2 Node Cluster

**Expected behavior**
Data should be processed only once,  not multiple times.

**Comment by mde2017** [comment] 2021-05-26 13:35
Linked pull request #4629

**Comment by ashvayka** [comment] 2021-05-26 15:02
Are you sure you have a unique Service-ID assigned to each service in your k8s scripts? This may be the root cause of the data duplication. See my comments here: https://github.com/thingsboard/thingsboard/pull/4629#issuecomment-848844916
The service id is defined using the TB_SERVICE_ID env variable.

**Closed** 2021-08-16 08:44 UTC
Labels: bug
