### ISSUE TITLE
How can you change the color of your widget background when it receives certain telemetry?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8779] opened 2023-06-19 01:55 UTC
Hi everyone,

I would like to have a card widget change background color when certain vales are returned. 

For example, I would like the color to change to Green when it receives the telemetry 2 and Red when it receives the telemetry 0. 
I have it now so that when the telemetry is 2 it returns with the word Manual mode. I would like it to also change the background color to green as well.

So when the value 2 is received the background color changes to Green and the word Manual mode appears.

Here what the card look like now.

![image](https://github.com/thingsboard/thingsboard/assets/130080104/b9ffe0c8-d29e-47b2-871b-c2cb85455f18)
![image](https://github.com/thingsboard/thingsboard/assets/130080104/5bbacd41-0d5b-46d8-b9b1-bff647d0f03f)

Thanks

**Comment by Ultrazombie** [comment] 2024-05-07 12:04
Closed as duplicate of https://github.com/thingsboard/thingsboard/issues/8791

**Closed by Ultrazombie** 2024-05-07 12:04 UTC
