### ISSUE TITLE
Can't create account on demo

### ISSUE THREAD

**Issue by doom369** [thingsboard/thingsboard#15] opened 2016-12-18 13:36 UTC
![screenshot-demo thingsboard io 2016-12-18 15-34-59](https://cloud.githubusercontent.com/assets/1536494/21293823/b4ef3e7e-c537-11e6-914a-54657e108a4a.png)

Nothing happens on click "Sign up". No errors.

**Comment by ashvayka** [comment] 2016-12-18 14:04
Hi!

Your password is too short. The password should be at least 6 chars. There is a popup validation message. Don't know why it is missing. What browser are you using?

**Comment by doom369** [comment] 2016-12-18 14:44
Chrome Version 55.0.2883.75 (64-bit)
Untuntu 16.04

**Comment by ashvayka** [comment] 2017-02-08 16:55
We can't reproduce this. Closing the issue.

**Closed by ashvayka** 2017-02-08 16:55 UTC
