### ISSUE TITLE
Error during building from source

### ISSUE THREAD

**Issue by sharmaChirayu** [thingsboard/thingsboard#482] opened 2017-12-15 09:29 UTC
I am trying to build thingsboard using the source code by following the guide at the following [link](https://thingsboard.io/docs/user-guide/install/building-from-source/)

I have the following configuration

- Ubuntu 16.04 LTS

- java version "1.8.0_151"

- Apache Maven 3.3.9

Firstly, when I try to clone the code using the `git clone git@github.com:thingsboard/thingsboard.git` command, I got the following error.
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I managed to clone the code using the web URL. However, when I try to build the code using the command `mvn clean install`, I get an error while running the DAO tests.

```
2017-12-15 09:15:15,916 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Changing key of admin settings entry is prohibited!]
2017-12-15 09:15:15,922 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Key should be specified!]
2017-12-15 09:15:15,942 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Provided json structure is different from stored one '{"mailFrom":"Thingsboard <sysadmin@localhost.localdomain>","smtpProtocol":"smtp","smtpHost":"localhost","smtpPort":"25","timeout":"10000","enableTls":"false","username":"","password":"","newKey":"my new value"}'!]
2017-12-15 09:15:35,371 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Asset should be assigned to tenant!]
2017-12-15 09:15:40,408 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Can't assign asset to non-existent customer!]
2017-12-15 09:15:40,452 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Asset is referencing to non-existent tenant!]
2017-12-15 09:15:40,491 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Can't assign asset to customer from different tenant!]
2017-12-15 09:15:46,733 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Asset name should be specified!]
2017-12-15 09:15:57,672 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Customer should be assigned to tenant!]
2017-12-15 09:16:02,345 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Invalid email address format 'invalid@mail'!]
2017-12-15 09:16:02,492 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Customer is referencing to non-existent tenant!]
2017-12-15 09:16:02,522 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Customer title should be specified!]
2017-12-15 09:16:40,803 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Can't assign dashboard to non-existent customer!]
2017-12-15 09:16:40,908 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Dashboard should be assigned to tenant!]
2017-12-15 09:16:40,945 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Can't assign dashboard to customer from different tenant!]
```
The final build results are as follows.

```
Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.820 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.098 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  8.976 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.375 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  0.717 s]
[INFO] Thingsboard Server DAO Layer ....................... FAILURE [03:13 min]
[INFO] Thingsboard Server Extensions API .................. SKIPPED
[INFO] Thingsboard Server Core Extensions ................. SKIPPED
[INFO] Thingsboard Extensions ............................. SKIPPED
[INFO] Thingsboard Server RabbitMQ Extension .............. SKIPPED
[INFO] Thingsboard Server REST API Call Extension ......... SKIPPED
[INFO] Thingsboard Server Kafka Extension ................. SKIPPED
[INFO] Thingsboard Server MQTT Extension .................. SKIPPED
[INFO] Thingsboard Server SQS Extension ................... SKIPPED
[INFO] Thingsboard Server SNS Extension ................... SKIPPED
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport ......................... SKIPPED
[INFO] Thingsboard COAP Transport ......................... SKIPPED
[INFO] Thingsboard MQTT Transport ......................... SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
```

So, I tried to build the code without running the tests using the command `mvn clean install -DskipTests`.
The previous error was avoided, however, I get the following error.

```
[WARNING] npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[WARNING] npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.674 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.100 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  7.677 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.396 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  0.760 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 12.868 s]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  1.748 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [  6.365 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.057 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  3.647 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  1.297 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  3.828 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  0.992 s]
[INFO] Thingsboard Server SQS Extension ................... SUCCESS [  4.700 s]
[INFO] Thingsboard Server SNS Extension ................... SUCCESS [  2.576 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.257 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  0.834 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  1.426 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  1.354 s]
[INFO] Thingsboard Server UI .............................. FAILURE [04:15 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:11 min
[INFO] Finished at: 2017-12-15T09:24:37+00:00
[INFO] Final Memory: 74M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 137) -> [Help 1]

```

Can somebody please help?

Thanks

**Comment by ethicstechOSS** [comment] 2017-12-15 11:25
What is your node and npm version?.

**Comment by closedDoor** [comment] 2017-12-15 12:28
My node version is **v8.9.3** and npm version is **5.5.1**

**Comment by ashvayka** [comment] 2018-01-08 21:04
Permissions?

**Comment by pushkar31** [comment] 2018-01-17 05:54
Today I tried "mvn clean install" and in output its giving error massage of npm installtion.
please find attached screenshot.
![error of npm](https://user-images.githubusercontent.com/30723922/35027842-f066b48c-fb78-11e7-8dca-e9e17ed98ec2.png)

Please which permission i need to check and how to set required permission.

**Comment by ehsanmqn** [comment] 2018-02-02 17:34
I am also encountered to this problem. Then, according to last line instruction I ran "sudo mvn -X install -rf :ui". Results generated as follow:

[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard Server UI .............................. FAILURE [04:20 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:21 min
[INFO] Finished at: 2018-02-02T12:31:36-05:00
[INFO] Final Memory: 13M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by alonsillo88** [comment] 2018-02-07 14:17
I've got the same Issue. I'm using AMAZON WS and I can't build from source, so I can't custom TB. Somebody help!

**Comment by closedDoor** [comment] 2018-02-14 08:14
Is there any update regarding this problem?

**Comment by mp-loki** [comment] 2018-04-20 03:51
@closedDoor is this still the case with the latest version?

**Comment by mysty-mystic** [comment] 2019-01-10 04:05
@mp-loki this is still a problem , no solution yet for this problem

**Comment by alexsmartens** [comment] 2019-04-17 20:01
I'm having a similar problem:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task
```

**Comment by volkanalkilic** [comment] 2019-05-07 11:30
same problem here!

**Comment by alexsmartens** [comment] 2019-05-07 15:55
Hi @volkanalkilic,

try [this suggestion](https://github.com/thingsboard/thingsboard/issues/883#issuecomment-399015292), that might be helpful

**Comment by Guilai1990** [comment] 2019-07-05 17:12
Hi guys, I encounter the same error with npm version 6.9.0 as well as node vesion10.16.0.
Anyone find the solution to fix this issue or ignore it?

**Comment by caoyingde** [comment] 2019-08-01 07:53
λ yarn -f install
yarn install v1.16.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning angular-ui-router@0.3.2: This npm package 'angular-ui-router' has been renamed to '@uirouter/angularjs'. Please update your package.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/
warning material-ui > react-addons-create-fragment > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
error Can't add "ngFlowchart": invalid package version "0.5.1TB".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by caoyingde** [comment] 2019-08-01 07:53
error Can't add "ngFlowchart": invalid package version "0.5.1TB".

**Comment by caoyingde** [comment] 2019-08-01 07:54
f:\git\thingsboard2.4.1\ui (master -> origin)
λ node -v
v12.6.0

f:\git\thingsboard2.4.1\ui (master -> origin)
λ npm -v
6.1.0

**Comment by martin-bozhilov** [comment] 2019-08-06 12:58
Hi guys!
I had the same issue. I successfully built the project in 2.4.0 release branch with "su" permissions:
```
$ su
$ mvn clean install -DskipTests
```
I'm using Manjaro Linux 18.0.4
Maven 3.6.1
npm 6.9.0
node v10.16.1

Hope this help!

**Comment by hamburml** [comment] 2019-12-06 12:40
I had the same issue.

I tried to build it locally on Ubuntu 18.04 with user rights and su rights. I used node v12. In the logfiles I saw that node v10 is installed locally when ui was build (i think it was ui, doesn't remember). I removed nodev12 and installed v10 and now it builds with user rights!

**Comment by hamza-atifi** [comment] 2020-05-01 06:17
I had the same issue. I used the latest version of maven and it did the job

**Comment by ashvayka** [comment] 2020-06-01 13:09
Thanks to @hamburml  we can close this now.

**Closed by ashvayka** 2020-06-01 13:09 UTC
