### ISSUE TITLE
On Windows, install_dev_db.bat can give success message even when it fails

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#311] opened 2017-09-28 21:37 UTC
On Windows, running install_dev_db.bat will report a success message, even when installation fails. 

````
c:\dev\thingsboard\application\target\windows>install_dev_db.bat
 ===================================================
 :: ThingsBoard ::       (v1.3.1-SNAPSHOT)
 ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5ECA6731DC.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ThingsBoard DB installed successfully!

c:\dev\thingsboard\application\target\windows>
````

Things look good, right?  They're not.

When I examine the created database, none of the thingsboard tables are present.  The reason it failed is there is another service bound to port 8080 which is causing a failure somewhere in the process.

When I kill that process, delete the previous database, and rerun install_dev_db.bat, I get the following output:

````
c:\dev\thingsboard\application\target\windows>install_dev_db.bat
 ===================================================
 :: ThingsBoard ::       (v1.3.1-SNAPSHOT)
 ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5ECA23D0E6.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Loading demo data...
Installation finished successfully!
ThingsBoard DB installed successfully!

c:\dev\thingsboard\application\target\windows>
````

This time the database has been properly created, and the expected tables are present.

I would expect that when there is a problem with the creation of the database, an appropriate error message would be printed, and, ideally, the partially created data tables deleted.

To reproduce, run the install script when port 8080 is bound to another process.

**Comment by mp-loki** [comment] 2017-09-29 03:13
Hi @eykamp 

Thank you for reporting this problem! This is a valid issue, however, it is not about the occupied port, but the database file lock. The actual error was:
`Caused by: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile:`

I assume you had the ThingsBoard process already running when trying to launch the install_dev_db.bat.
The problem here was that the installer application did not maintain the error code correctly, that's why the script was printing the 'ThingsBoard DB installed successfully!' message.

I have submitted a PR which fixes the error code and adds logging to the console to avoid confusion when the installation error happens.

https://github.com/thingsboard/thingsboard/pull/312

Thank you,
Valerii Sosliuk

**Comment by eykamp** [comment] 2017-09-29 04:17
The real issue is the process reporting success when it has in fact failed. The reason for the failure is less important.

I suspect the fix will involve checking exit codes.

Chris

**Comment by mp-loki** [comment] 2017-09-29 19:17
PR with the fix merged

**Closed** 2017-10-16 08:28 UTC
