### ISSUE TITLE
PE Mobile App Error While Uploading To Google Play Store

### ISSUE THREAD

**Issue by nikolamaksim1** [thingsboard/thingsboard#10023] opened 2024-01-19 13:58 UTC
I saw exactly the same issue but it was a closed one and the answer wasn't there.
https://github.com/thingsboard/thingsboard/issues/9615

**Comment by ashvayka** [comment] 2024-01-19 16:59
I have replied to the reference issue. The issue here is with the package name. The same package name is used by ThingsBoard Inc to publish the sample app. One should change the "org.thingsboard.pe..." to something unique. Usually, the reversed domain of the company.

**Comment by nikolamaksim1** [comment] 2024-01-19 17:27
like com.mycompany?

**Comment by nikolamaksim1** [comment] 2024-01-20 16:21
I have changed them but the same error still occurs.

**Comment by nikolamaksim1** [comment] 2024-01-20 16:21
![Screenshot 2024-01-21 012035](https://github.com/thingsboard/thingsboard/assets/156649370/169600ad-5406-4cf1-a1f9-29e0a6b18b10)

**Comment by nikolamaksim1** [comment] 2024-01-22 10:14
I am wondering if there's another modification to be applied but I have missed.

**Comment by Ultrazombie** [comment] 2024-11-22 15:28
Hello @nikolamaksim1 
Please try to ask this question on the relevant repository if the issue is actual:
https://github.com/thingsboard/flutter_thingsboard_pe_app/issues
I'll close this issue here due to another project.

**Closed by Ultrazombie** 2024-11-22 15:28 UTC
