### ISSUE TITLE
CE Upgrading 3.6.2 to 3.6.3 ... ERROR

### ISSUE THREAD

**Issue by carlospintojunior** [thingsboard/thingsboard#10427] opened 2024-03-23 15:38 UTC
**Describe the bug**
Version 3.6.2 was working normally, at least that was my impression.
I followed the steps recommended in:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-363
When updating to version 3.6.3 an error appeared during the process:

~~~
Starting ThingsBoard Upgrade from version 3.6.2 ...
Upgrading ThingsBoard from version 3.6.2 to 3.6.3 ...
Updating schema ...
Skip schema re-update to version 3.6.3. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Updating default edge failure notification configs for all tenants
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Starting rule nodes upgrade ...
Finished rule nodes upgrade. Upgraded rule nodes count: 0
Loading system widgets
Unable to load widget type from json: [/usr/share/thingsboard/data/json/system/widget_types/battery_level.json]
Unexpected error during ThingsBoard installation!
~~~

**Your Server Environment**

* own setup
  * Deployment type: thingsboard-3.6.3.deb
  * ThingsBoard Version 3.6.2 -> 3.6.3
  * Community Edition
  * Description:    Ubuntu 20.04.6 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 22.04.4 LTS
* Browser: google-chrome 
* Version: 122.0.6261.128

**To Reproduce**
1. wget https://github.com/thingsboard/thingsboard/releases/download/v3.6.3/thingsboard-3.6.3.deb
2. sudo service thingsboard stop
3. sudo dpkg -i thingsboard-3.6.3.deb
4. sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.6.2

**Unexpected result**
~~~
Starting ThingsBoard Upgrade from version 3.6.2 ...
Upgrading ThingsBoard from version 3.6.2 to 3.6.3 ...
Updating schema ...
Skip schema re-update to version 3.6.3. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Updating default edge failure notification configs for all tenants
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Starting rule nodes upgrade ...
Finished rule nodes upgrade. Upgraded rule nodes count: 0
Loading system widgets
Unable to load widget type from json: [/usr/share/thingsboard/data/json/system/widget_types/battery_level.json]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to load widget type from json
        at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:249)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.thingsboard.server.service.install.InstallScripts.loadSystemWidgets(InstallScripts.java:241)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.loadSystemWidgets(DefaultSystemDataLoaderService.java:495)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:139)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.thingsboard.server.dao.resource.BaseImageService$$EnhancerBySpringCGLIB$$1622039a.replaceBase64WithImageUrl(<generated>)
        at org.thingsboard.server.dao.widget.WidgetTypeServiceImpl.saveWidgetType(WidgetTypeServiceImpl.java:97)
        at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:246)
        ... 13 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
~~~

**Additional context**
1. The MQTT service still works.
2. I performed a fresh installation of version 3.6.3 in another environment and tried to import the widgets. The error message appears:
**Transaction silently rolled back because it has been marked as rollback-only.**
3. I tried to create widgets manually and received the following error message:
**GET: /api/widgetType?fqn=system.charts.basic_timeseries 404: OK**
4. Apparently the system is working, with the exception of the widgets.
![Screenshot from 2024-03-23 11-08-31](https://github.com/thingsboard/thingsboard/assets/36606089/9f145332-461a-434d-8d2a-43919b93315d)

My knowledge of Java is low. What can I do to help resolve this issue?

**Comment by sudhirbits** [comment] 2024-03-28 06:42
Hitting the same issue but for action_button.json. The result is the same the dashboard widgets are not loading with the same error message.

**Comment by sudhirbits** [comment] 2024-03-28 08:01
`Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only` this appears to be a code issue?

**Comment by trikimiki** [comment] 2024-04-19 11:33
Hi

The problem is that either there is no file present in the directory provided in the error message
or there is a wrong or outdated config present in your system.

Check #9693 and #9324 for more info.

Your `thingsboard.conf` should look like this
```
export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql
```

**Comment by carlospintojunior** [comment] 2024-04-19 11:43
Dear
Thank you for the information. I ended up solving it another way and deploying a new version 3.6.3.
I don't know the issue rules very well. Can I close this issue?

**Closed** 2024-04-22 11:21 UTC
Labels: bug, unconfirmed

**Comment by sudhirbits** [comment] 2024-06-05 04:50
This was solved by using the following method. 

1. Ran another docker container for `tb-postgres` specifying version as 3.6.3 (no upgrade) => `mytb1`
2. Connecting to the docker container `mytb1` I exported data for the following tables 1. `widget_type` 2. `widgets_bundle` and 3. `widgets_bundle_widget` 
3. Data was imported into the main docker container postgres database.
