### ISSUE TITLE
[Bug] Trip Animation Widget time arrows not working correctly

### ISSUE THREAD

**Issue by JaMurphSmi** [thingsboard/thingsboard#4763] opened 2021-06-18 16:02 UTC
ThingsBoard V3.1.1/v3.2.2

I am making a dashboard making use of the Trip Animation widget. When I simply press the play button and the timing is set to 25, and then press any of the buttons marked below, it goes directly to start or end, and don't work again afterwards.
![image](https://user-images.githubusercontent.com/22885637/122579781-2b277f00-d04d-11eb-8af7-13cdda2775f0.png)

**Comment by LeoMorgan113** [comment] 2021-06-24 10:39
Hi @JaMurphSmi,

Unfortunately, I cannot reproduce your bug, for everything works correctly.
Could you give more details?
I may suppose that your time period is too small that it jumps to the end.

Anyway, this widget has many known bugs, which will be fixed most likely in the new release, v3.3.

**Closed** 2021-09-01 11:25 UTC
Labels: bug
