### ISSUE TITLE
[Bug] Thingsboard upgrade to 3.4.2PE from 3.4.1PE

### ISSUE THREAD

**Issue by xeeed-k1** [thingsboard/thingsboard#7841] opened 2022-12-25 08:15 UTC
**Describe the bug**
Login to the thingsboard fails after upgrade to 3.4.2PE from 3.4.1PE
with 500: OK Close error.

**Your Server Environment**
* own setup
  * cloud on AWS
  * ThingsBoard Version - 3.4.2PE
  * OS Name and Version - Ubuntu

**To Reproduce**
TB 3.4.1 deployed in AWS EC2
1. Stop the thingsboard service
`sudo systemctl stop thingsboard`
2. Stop the EC2 instance
3. Take the snapshot
4. Start the EC2 instance
5. Stop TB Service
`sudo systemctl stop thingsboard`
6. Upgrade TB
`cd upgrades 
wget https://dist.thingsboard.io/thingsboard-3.4.2pe.deb

sudo dpkg -i thingsboard-3.4.2pe.deb
Merge option is to be used.

##### Execute regular upgrade script
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.4.1

sudo systemctl daemon-reload
sudo service thingsboard start`

**Expected behavior**
Login to happen normally when upgrade is performed and the services are started.

**Comment by trikimiki** [comment] 2022-12-28 13:44
The error 500 indicates that there are some issues with the backend.
Could you share the log file (`/var/log/thingsboard/thingsboard.log`) after reproducing the issue (login with 500 error)?

**Comment by jsobieski** [comment] 2022-12-29 02:23
We also are having login issues after upgrading to 3.4.2PE from 3.4.1PE. Login as SYSADMIN works fine but login as a tenant admin for most tenants results in a java.lang.NullPointerException

**Comment by trikimiki** [comment] 2023-01-09 13:47
Please provide logs after reproducing the error. The stacktrace in the log file might have a hint.
Also, could you try checking dev console (f12) to see what exact request causing the error?

**Comment by HaydenBurrows** [comment] 2023-01-13 03:06
@jsobieski I have had the same issue in #7731. @den1jkee mentioned that this error was fixed in 3.4.3.  I updated to 3.4.3 and everything is normal again.

**Comment by lsolisc** [comment] 2023-01-27 06:16
I have the same error in 3.4.3PE

**Comment by xeeed-k1** [comment] 2023-02-12 19:10
I am sharing log file in the support portal, thank you!

> The error 500 indicates that there are some issues with the backend. Could you share the log file (`/var/log/thingsboard/thingsboard.log`) after reproducing the issue (login with 500 error)?

**Comment by trikimiki** [comment] 2023-09-27 11:40
If the issue is still relevant - could you please provide log files after failed service startup?

**Closed** 2023-10-12 11:47 UTC
