### ISSUE TITLE
[Question] No data found in Timeseries table

### ISSUE THREAD

**Issue by JKYLien** [thingsboard/thingsboard#6238] opened 2022-03-11 08:40 UTC
Hello, everyone
Sorry for asking some unwise questions

I want to build a Timeseries table in the dashboard.
But according to the current settings, I don't know why the data can't be displayed all the time.
The time setting is also within the range, and even the data within 100 days cannot be searched.
Attaching the current settings here, sorry for the many stupid names due to testing.
Thanks

![未命名2](https://user-images.githubusercontent.com/97505009/157832273-0b87babe-1d53-4ed3-b03e-f9e07de8f5f4.png)
![未命名4](https://user-images.githubusercontent.com/97505009/157832355-33c3cd20-aba8-40f3-9320-95ae6ca96182.png)
![未命名](https://user-images.githubusercontent.com/97505009/157832367-aece776d-7c57-45c0-9925-a54aad270113.png)
![未命名3](https://user-images.githubusercontent.com/97505009/157832372-db225239-e2fe-40fb-b01c-6ff3194cd5e1.png)

**Comment by justsomeguyontheinternet** [comment] 2022-03-13 03:00
i see the same issue since upgrading to 3.3.4

**Comment by MJosipovi** [comment] 2022-07-19 07:45
Hi, same issue.
Solution: just turn on "Use post-processing function" on your timeseries (at that Timeseries table widget), and leave it on deafult "return value;". Observe the picture.

Btw. if you do what I stated as solution, and then reverse it (untick checkbox), it will still display data correctly until you refresh the page.

And yes, this is some kind of a bug that needs to be solved. 
I will notify ThingsBoard team via my support panel.

If possible, change this thread from question to bug.

![image](https://user-images.githubusercontent.com/84789931/179694307-9440a36b-4009-4e69-9e7d-e84159a862e1.png)

**Comment by epalchenko** [comment] 2024-05-21 07:17
Hello,
This behavior is not reproduced after v3.3.4.1. I am closing this ticket as solved. 
Please re-create the new ticket with detailed steps to reproduce if this problem still exists.

**Closed by epalchenko** 2024-05-21 07:17 UTC
Labels: question
