### ISSUE TITLE
onMouseDownhandler 

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#1456] opened 2019-02-05 09:46 UTC
Shouldn't i be able to do this? For some reason this dosen't work..
I want to be able to click anywere on the widget and get a response that i have "_**Clicked!**_"??
Please help.
![pic](https://user-images.githubusercontent.com/31566100/52264914-0ece9000-2933-11e9-89ee-13d1dd6b225c.png)

**Comment by vparomskiy** [comment] 2019-02-06 09:26
I think it is a duplicate of this issue https://github.com/thingsboard/thingsboard/issues/403

**Closed** 2022-06-20 12:07 UTC
