### ISSUE TITLE
dashboard updates widgets x.y if I change background color

### ISSUE THREAD

**Issue by juanpgg-git** [thingsboard/thingsboard#11828] opened 2024-10-09 12:28 UTC
**Describe the bug**
I have a dashboard with a few widgets. They all fit on my screen. When I change the background color in the layout, one of the widgets disappears. If I add an HTML card to show an image, it disappears if I change the color. 

This is on the web version

**Expected behavior**
I expect the widgets to remain in the same position after I change the dashboard background color

**Screenshots**
![image](https://github.com/user-attachments/assets/28ca7c3e-4523-4ec6-b2ef-39e9e5cb8417)
![image](https://github.com/user-attachments/assets/e9fa6144-eeab-4985-9957-1827192912a8)

**Comment by dealnat** [comment] 2024-10-10 14:22
Hello, It seems like you first add a widget but don't save the dashboard, and then you change layout settings that override dashboard changes, so you need to make changes in the dashboard, like adding a new widget, then save the dashboard, and only after that change layout settings.

**Comment by juanpgg-git** [comment] 2024-10-10 14:27
Hi @dealnat , I didn't save my dashboard before and faced that issue, so I can confirm all the widgets in that picture are already saved. 

But the problem persist

**Comment by dealnat** [comment] 2024-10-10 14:33
Hi, I can't reproduce the issue on my instance. Can you please provide detailed steps for reproducing it? Also, video recording would be great.

**Comment by juanpgg-git** [comment] 2024-10-10 14:41
[ThingsBoard Cloud _ Dashboard - Brave 2024-10-10 09-37-27.zip](https://github.com/user-attachments/files/17329904/ThingsBoard.Cloud._.Dashboard.-.Brave.2024-10-10.09-37-27.zip)

I think it has to do with the "width" of the dashboard, besides that, I don't have any more ideas

**Comment by dealnat** [comment] 2024-10-11 15:43
Hi, yes, I reproduced the issue and can confirm that it's present on the cloud platform. However, after the upgrade on 15.10.24, this issue will be fixed.

**Comment by juanpgg-git** [comment] 2024-10-11 17:51
thanks

**Comment by dealnat** [comment] 2024-10-15 07:41
@juanpgg-git cloud platform is upgraded now. Please try to see if the issue is resolved.

**Comment by juanpgg-git** [comment] 2024-10-19 15:46
Solved

**Closed** 2024-10-19 15:46 UTC
Labels: bug, unconfirmed
