### ISSUE TITLE
[Bug] Building from sources

### ISSUE THREAD

**Issue by Nour-25** [thingsboard/thingsboard#6391] opened 2022-04-07 21:25 UTC
**Describe the bug**
I can't build the project using Maven tool

- (mvn clean install -DskipTests ) 

- (mvn clean install -DskipTests -Ddockerfile.skip=false) 

- (mvn dependency:purge-local-repository)

why maven couldn't complete the build?
the build stops at Thingsboard Server Common Utils 
for example one  of the dependency is in: https://repo1.maven.org/maven2/org/awaitility/awaitility/4.1.0/awaitility-4.1.0.jar and maven can find it

but  for 'https://repo1.maven.org/maven2/org/thingsboard/common/data/3.3.4.1/data-3.3.4.1.jar
maven could not find artifact org.thingsboard.common:data:jar:3.3.4.1 in central (https://repo1.maven.org/maven2/) and when I look for this jar to download it I can't find it  in https://repo1.maven.org/maven2/org/thingsboard/ 

there isn't  /common/data/[3.3.4.1/](http://3.3.4.1/) then i searched for  thingsboard common data jar  in google but i can't find it either 
you can find also in the attached files the error block note

i have cleared the cache for serval times [clean maven cache , gradle cache,node modules]
 ** Environment **

  * OS Name : Windows  
  * -java version: java 11
  *  maven
  * nodejs v16.13.0
  * yarn v 1.22.17
  * npm 
  * IntelliJ IDEA
  *  docker desktop 
  
[error.txt](https://github.com/thingsboard/thingsboard/files/8446568/error.txt)

**Comment by Backdraft007** [comment] 2022-04-07 21:39
Hi,
I'm not familar with windows installations. But, why you build it from source? Is there a special reason?

FYI, windows installation is deprecated.

**Comment by Nour-25** [comment] 2022-04-07 21:51
hi , 
I also try to build it from source in ubuntu 20.04 and 21.10 
and the build stops at ThingsBoard Server UI

**Comment by Backdraft007** [comment] 2022-04-07 22:03
Ok,
I think then you did something wrong. ;)
I recommend to use Linux as server. I use Debian and have no problems. I built the source last week to check something and I had no problems.

For production and testing I use only the dep installation.

Is there a reason to build it from source?

**Comment by Nour-25** [comment] 2022-04-07 22:12
a school project to edit and add some features to an  open-source IoT platform

**Comment by Backdraft007** [comment] 2022-04-07 22:17
Ok,
as I said, I recommend Linux. Give it a try with Ubuntu or Debian. Are there problems let us know and we can handle this. 
Do you have built the source without your edits and adds?

**Comment by Nour-25** [comment] 2022-04-07 22:35
yes I just clone the project as it is and then I try to build it following the contributor guide

**Comment by Backdraft007** [comment] 2022-04-08 08:12
Can you give the error and logs.

**Comment by Nour-25** [comment] 2022-04-08 14:53
ubuntu 21.10
**_installation of required tools:_**

1-docker 
2-docker-compose
3- java 11
4-maven

**_cloning the source code of the forked project:_**

1-git clone
2- cd thingsboard
3-git checkout release-3.3

**_Build :_** 

**1-first methode**

(mvn clean install -DskipTests) or (mvn clean install -DskipTests -Ddockerfile.skip=false)
![mvn cl in  0](https://user-images.githubusercontent.com/73799845/162455432-82b8869a-4168-439a-922d-18697a14cdcb.PNG)
![mvn cl in  1](https://user-images.githubusercontent.com/73799845/162448849-9e818797-3a9d-4832-8b91-ba782e5ae3de.PNG)
![mvn cl in 2](https://user-images.githubusercontent.com/73799845/162449060-682deccf-8dce-4b6e-be56-869a720404aa.PNG)
![mvn cl in 3](https://user-images.githubusercontent.com/73799845/162449186-eb10b66b-1b8a-4e54-ae69-96326c380c26.PNG)
![mvn cl in 4](https://user-images.githubusercontent.com/73799845/162449407-b7a45ad8-5692-4cee-9a8a-0836bac0e81b.PNG)
![mvn cl in  5](https://user-images.githubusercontent.com/73799845/162449459-b2d71c93-06a7-497e-8576-549f0b70b2c2.PNG)
![mvn cl in  6](https://user-images.githubusercontent.com/73799845/162449535-71c153fc-3423-4f0a-9974-20fc4bc39a2a.PNG)

**2-second methode** 

mvn dependency:purge-local-repository -DactTransitively=false
![local rep 0](https://user-images.githubusercontent.com/73799845/162460889-f0992ae1-8331-4595-85a2-2b4e72acf6dc.PNG)
![local rep 1](https://user-images.githubusercontent.com/73799845/162461130-51e08ce4-10cc-4a5d-8889-3753fbe1e1f4.PNG)
![local rep 2](https://user-images.githubusercontent.com/73799845/162461402-ffd4d3e5-bab6-419a-88f7-9fccd14c32f6.PNG)
![local rep 3](https://user-images.githubusercontent.com/73799845/162461555-8dd60dc6-92ae-46fe-9a19-7499c44dc547.PNG)
![local rep 4](https://user-images.githubusercontent.com/73799845/162461782-2b405f53-7840-4667-a3d8-6d671266c92c.PNG)
![local rep 5](https://user-images.githubusercontent.com/73799845/162461959-5c4a1de5-c65e-4de3-b505-8a7a0f0bb380.PNG)

**3-third methode** 
_step1:_

 (mvn clean install -DskipTests -Ddockerfile.skip=false) or (mvn clean install -DskipTests)
![Capture 1](https://user-images.githubusercontent.com/73799845/162435960-ec356925-f7f7-4315-853a-d98ef0a982d2.PNG)
![Capture 2](https://user-images.githubusercontent.com/73799845/162436038-06681f31-ccfe-4a44-baed-aabc62ad935a.PNG)
_step2 :_

 mvn dependency:purge-local-repository -DactTransitively=false -rf :ui-ngx
![Capture 3](https://user-images.githubusercontent.com/73799845/162436152-1721ac1c-9eca-4b2d-bf7a-bc9f091cab1c.PNG)
![Capture 4](https://user-images.githubusercontent.com/73799845/162436190-48515754-e1a3-4c71-baaf-ac07b6722c22.PNG)
![Capture 5](https://user-images.githubusercontent.com/73799845/162436242-048c697b-8ade-4789-af7c-db805d9b7e95.PNG)

_step3:_
 no matter how i change the command i couldn't build the project

**Comment by devaskim** [comment] 2022-04-11 08:45
On the first screen I see that your code is located in /root directory. It is not a good idea, use /home/<your_user_name>/....
Secondly, go to the thingsboard/ui-ngx folder, run `yarn install` manually and post build log here (preferably in txt format)

**Comment by Nour-25** [comment] 2022-04-12 11:49
Is there any solution to resolve this?

**Comment by Nour-25** [comment] 2022-04-12 19:47
yes

**Comment by Backdraft007** [comment] 2022-04-13 10:18
Did you try this?
> Secondly, go to the thingsboard/ui-ngx folder, run `yarn install` manually and post build log here (preferably in txt format)

**Comment by Nour-25** [comment] 2022-04-13 21:24
yes I did and I've posted the log file

**Comment by Nour-25** [comment] 2022-04-13 21:27
HI
After removing everything ,I've used the /home/<your_user_name>/  but the problem remains 
then i've installed yarn in the ui-ngx folder  manually.
the attachments are the build log files
[mvn cl in-e.txt](https://github.com/thingsboard/thingsboard/files/8484750/mvn.cl.in-e.txt)
[mvn cl in-X.txt](https://github.com/thingsboard/thingsboard/files/8484754/mvn.cl.in-X.txt)

**Comment by Backdraft007** [comment] 2022-04-14 11:30
How do you cloned the source code?
`git clone git@github.com:thingsboard/thingsboard.git`
or another way?

**Comment by ChantsovaEkaterina** [comment] 2022-04-14 18:18
Hello,
Please, see this #6298.
This could  be a reason for which yarn install fails.

**Comment by Nour-25** [comment] 2022-04-15 12:39
HI
i forked the repo then
git clone  https://github.com/Nour-25/thingsboard.git

***@***.***:thingsboard/thingsboard.git can't be cloned
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists)

**Comment by Nour-25** [comment] 2022-04-15 12:40
> How do you cloned the source code? `git clone git@github.com:thingsboard/thingsboard.git` or another way?
HI
i forked the repo then
git clone  https://github.com/Nour-25/thingsboard.git

***@***.***:thingsboard/thingsboard.git can't be cloned
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists)

**Comment by Nour-25** [comment] 2022-04-15 21:09
> Hello, Please, see this #6298. This could be a reason for which yarn install fails.

hi 
i replaced git by https yarn install worked but  maven couldn't complete the build

**Comment by georgemichalis** [comment] 2022-04-18 10:49
Hi Everyone. Same exact issue on new clean VM of ubuntu 20.04 LTS. 
Trying manually the yarn install on ui-ngx folder results in the following

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/thingsboard/flot.git
Directory: /home/XXXX/tb/thingsboard/ui-ngx
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It appears that the issue is related to this 
[](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git)
and the git:// url

**Comment by georgemichalis** [comment] 2022-04-18 11:46
fixed by doing this:
on the main thingsboard folder folder paste `git config --global url."https://github.com/".insteadOf git://github.com/`

by navigate to folder `ui-ngx`  and use the files from the latest branch 

https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/package.json
https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/yarn.lock

Alternative open the files directly and replace `git://` with `https://` and it should compile

**Comment by Nour-25** [comment] 2022-04-18 14:28
> 



> fixed by doing this: on the main thingsboard folder folder paste `git config --global url."https://github.com/".insteadOf git://github.com/`
> 
> by navigate to folder `ui-ngx` and use the files from the latest branch
> 
> https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/package.json https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/yarn.lock
> 
> Alternative open the files directly and replace `git://` with `https://` and it should compile

Hi,
I ve open the files directly and replace `git://` with `https:// and this is the result :
[yarn_install.txt](https://github.com/thingsboard/thingsboard/files/8506193/yarn_install.txt)
then I run mvn clean install -DskipTests in thingsboard folder but the compile never completes and doesn't show an error either
  
`

**Comment by georgemichalis** [comment] 2022-04-19 05:41
> > 
> 
> > fixed by doing this: on the main thingsboard folder folder paste `git config --global url."https://github.com/".insteadOf git://github.com/`
> > by navigate to folder `ui-ngx` and use the files from the latest branch
> > https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/package.json https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/yarn.lock
> > Alternative open the files directly and replace `git://` with `https://` and it should compile
> 
> Hi, I ve open the files directly and replace `git://` with `https:// and this is the result : [yarn_install.txt](https://github.com/thingsboard/thingsboard/files/8506193/yarn_install.txt) then I run mvn clean install -DskipTests in the thingsboard folder but the compiling never completes and doesn't show an error either
> 
> `

just hangs there?

Are you using a VM or a normal installation?
In any case, i can confirm that it works on a new VM installation of Ubuntu 20.04, directly after the first boot and without any updates, with the following steps because i just tested that. The system needs 6gb of ram because yarn will run out of memory on the UI compilation. It also needs around 30gb hard drive

install java
```
sudo apt update
sudo apt install openjdk-11-jdk
```

```
sudo update-alternatives --config java
```

```
java -version
```

install curl

```
sudo apt install -y curl
```

install maven
```
sudo apt-get install maven
```


install node

```
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
```
```
sudo apt install -y nodejs
```

install yarn
```

sudo apt-get update && sudo apt-get install yarn
```

install git
```
sudo apt install git
```

since its a new installation at any point it will complain that the apt files are locked by the updater of PIDNUMBER whatever. You can do `sudo kill -9 PIDNUMBER` to skip that.  Personally i updated the system after the git installation with `sudo apt-get upgrade`

at this point you can pull the thingsboard repo, switch to 3.3 and build as normally.

**Comment by Backdraft007** [comment] 2022-04-19 07:03
Create a ssh key-pair and all things are good.
https://jhooq.com/github-permission-denied-publickey/#1-github---how-to-fix-this-issue

**Comment by moayyaed** [comment] 2022-04-20 17:48
> ubuntu 21.10 **_installation of required tools:_**
> 
> 1-docker 2-docker-compose 3- java 11 4-maven
> 
> **_cloning the source code of the forked project:_**
> 
> 1-git clone 2- cd thingsboard 3-git checkout release-3.3
> 
> **_Build :_**
> 
> **1-first methode**
> 
> **(mvn clean install -DskipTests) or (mvn clean install -DskipTests -Ddockerfile.skip=false)**
> 
> ![mvn cl in 0](https://user-images.githubusercontent.com/73799845/162455432-82b8869a-4168-439a-922d-18697a14cdcb.PNG) ![mvn cl in 1](https://user-images.githubusercontent.com/73799845/162448849-9e818797-3a9d-4832-8b91-ba782e5ae3de.PNG) ![mvn cl in 2](https://user-images.githubusercontent.com/73799845/162449060-682deccf-8dce-4b6e-be56-869a720404aa.PNG) ![mvn cl in 3](https://user-images.githubusercontent.com/73799845/162449186-eb10b66b-1b8a-4e54-ae69-96326c380c26.PNG) ![mvn cl in 4](https://user-images.githubusercontent.com/73799845/162449407-b7a45ad8-5692-4cee-9a8a-0836bac0e81b.PNG) ![mvn cl in 5](https://user-images.githubusercontent.com/73799845/162449459-b2d71c93-06a7-497e-8576-549f0b70b2c2.PNG) ![mvn cl in 6](https://user-images.githubusercontent.com/73799845/162449535-71c153fc-3423-4f0a-9974-20fc4bc39a2a.PNG)
> 
> **2-second methode**
> 
> **mvn dependency:purge-local-repository -DactTransitively=false** ![local rep 0](https://user-images.githubusercontent.com/73799845/162460889-f0992ae1-8331-4595-85a2-2b4e72acf6dc.PNG) ![local rep 1](https://user-images.githubusercontent.com/73799845/162461130-51e08ce4-10cc-4a5d-8889-3753fbe1e1f4.PNG) ![local rep 2](https://user-images.githubusercontent.com/73799845/162461402-ffd4d3e5-bab6-419a-88f7-9fccd14c32f6.PNG) ![local rep 3](https://user-images.githubusercontent.com/73799845/162461555-8dd60dc6-92ae-46fe-9a19-7499c44dc547.PNG) ![local rep 4](https://user-images.githubusercontent.com/73799845/162461782-2b405f53-7840-4667-a3d8-6d671266c92c.PNG) ![local rep 5](https://user-images.githubusercontent.com/73799845/162461959-5c4a1de5-c65e-4de3-b505-8a7a0f0bb380.PNG)
> 
> **3-third methode** _step1:_
> 
> **(mvn clean install -DskipTests -Ddockerfile.skip=false) or (mvn clean install -DskipTests)** ![Capture 1](https://user-images.githubusercontent.com/73799845/162435960-ec356925-f7f7-4315-853a-d98ef0a982d2.PNG) ![Capture 2](https://user-images.githubusercontent.com/73799845/162436038-06681f31-ccfe-4a44-baed-aabc62ad935a.PNG) _step2 :_
> 
> **mvn dependency:purge-local-repository -DactTransitively=false -rf :ui-ngx** ![Capture 3](https://user-images.githubusercontent.com/73799845/162436152-1721ac1c-9eca-4b2d-bf7a-bc9f091cab1c.PNG) ![Capture 4](https://user-images.githubusercontent.com/73799845/162436190-48515754-e1a3-4c71-baaf-ac07b6722c22.PNG) _step3:_ **mvn -T 0.8C license:format clean install -DskipTests -Ddockerfile.skip=false**
> 
> ![Capture 5](https://user-images.githubusercontent.com/73799845/162436242-048c697b-8ade-4789-af7c-db805d9b7e95.PNG)
> 
> _step4:_ no matter how i change the command i couldn't build the project

hi Nour,

I tried to build the current source code with the steps that published on thingsboard website using Ubuntu 20,Debian 11,windows 10,and windows 11, but the build failed with the error you got.
I would to dive more to find the issue but right now I can build the source using same steps  on thingsboard website by checkout source code to flow Commit hash "be806743ef7bda789c3860855d81bff55c00540f".

try to do this and feed me back :)

**Comment by Backdraft007** [comment] 2022-04-21 06:38
Yes to options. Use master source code or create ssh key pair and add it at github:
https://jhooq.com/github-permission-denied-publickey/#1-github---how-to-fix-this-issue

**Comment by gooama** [comment] 2022-04-21 17:53
First try a forced update:

`mvn clean install -U -DskipTests`

If the forced update does not work there IS something wrong. Check the following things: Broken local artifacts - go to you local maven repository and search for the artifact and delete the folder. (in win usually under C:\Documents and Settings{your-username}.m2, in linux ~/.m2) Is the artifact ACTUALLY on the repo, check spelling, version, everything! Is the connection to the repo possible, watchout for proxy settings!

**Comment by Nour-25** [comment] 2022-04-22 22:34
> > > 
> > 
> > 
> > > fixed by doing this: on the main thingsboard folder folder paste `git config --global url."https://github.com/".insteadOf git://github.com/`
> > > by navigate to folder `ui-ngx` and use the files from the latest branch
> > > https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/package.json https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/yarn.lock
> > > Alternative open the files directly and replace `git://` with `https://` and it should compile
> > 
> > 
> > Hi, I ve open the files directly and replace `git://` with `https:// and this is the result : [yarn_install.txt](https://github.com/thingsboard/thingsboard/files/8506193/yarn_install.txt) then I run mvn clean install -DskipTests in the thingsboard folder but the compiling never completes and doesn't show an error either
> > `
> 
> just hangs there?
> 
> Are you using a VM or a normal installation? In may experience, i prefer to do these kind of installs in a Virtual machine so i can have a known state of the system and take snapshots and try stuff. In any case, i can confirm that it works on a new VM installation of Ubuntu 20.04, directly after the first boot and without any updates with the following steps because i just re-tested that. The system needs 6gb of ram because yarn will run out of memory on the UI compilation. It also needs around 30gb hard drive during compilation. (i am not sure exactly how much, but i can tell you that 20 wasn't enough and i had to resize) so...
> 
> install java
> 
> ```
> sudo apt update
> sudo apt install openjdk-11-jdk
> ```
> 
> ```
> sudo update-alternatives --config java
> ```
> 
> ```
> java -version
> ```
> 
> install curl
> 
> ```
> sudo apt install -y curl
> ```
> 
> install maven
> 
> ```
> sudo apt-get install maven
> ```
> 
> install node
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
> ```
> 
> ```
> sudo apt install -y nodejs
> ```
> 
> install yarn
> 
> ```
> 
> sudo apt-get update && sudo apt-get install yarn
> ```
> 
> install git
> 
> ```
> sudo apt install git
> ```
> 
> since its a new installation at any point it will complain that the apt files are locked by the updater of PIDNUMBER whatever. You can do `sudo kill -9 PIDNUMBER` to skip that. Personally i updated the system after the git installation with `sudo apt-get upgrade`. I recommend to do it that order because of some yarn issues that i saw.
> 
> if you also want to install npm do it after the upgrade
> 
> install npm
> 
> ```
> sudo apt install npm
> ```
> 
> at this point you can pull the thingsboard repo, switch to 3.3 and build as normally after doing this:
> 
> on the main thingsboard folder folder paste git config --global url."[https://github.com/".insteadOf](https://github.com/%22.insteadOf) git://github.com/
> 
> by navigate to folder ui-ngx and use the files from the latest branch
> 
> https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/package.json https://raw.githubusercontent.com/vvlladd28/thingsboard/697965d3cac70b3905545a6a55a62fecf7c53200/ui-ngx/yarn.lock

thanks for every one how helped me  the project is successfully builded  and the problem is that yarn run out of memory on the UI compilation under 6gb of ram

**Comment by Nour-25** [comment] 2022-04-23 00:22
i m facing a new issue when i run the main method of org.thingsboard.server.ThingsboardServerApplication class that is located in application module from your IDE
[run_prb.txt](https://github.com/thingsboard/thingsboard/files/8545229/run_prb.txt)
is there a farther configuration or missing steps?
.

**Comment by Backdraft007** [comment] 2022-04-25 07:01
Postgres is running?

**Comment by Nour-25** [comment] 2022-04-26 10:09
> Postgres is running?

yes

**Comment by Nour-25** [comment] 2022-04-29 00:08
hi , 
org.thingsboard.server.gen.transport.TransportProtos
TransportProtos make  errors and i couldn't find the jar or the maven dependency 
i think that's why the platform isn't running  
is there a solution

**Comment by moayyaed** [comment] 2022-04-29 01:15
> 

Hi ,

I flow the steps as mentioned above on 
windows 11 environment 
Openjdk 11
But still the server ui build failed .

So please any advice.

**Comment by Nour-25** [comment] 2022-04-29 04:15
> > 
> 
> Hi ,
> 
> I used the steps as mentioned above on windows 11 environment Openjdk 11 But still the server ui build failed .
> 
> So please any advice.

i can confirm that the build  works on  Ubuntu 20.04, directly after the first boot and without any updates with i just re-tested that. The system needs 6gb of ram because yarn will run out of memory on the UI compilation. It also needs around 30gb hard drive during compilation.
follow the steps above of georgemichalis comment and don't forget to install and run postgres pgadmin4 to create the thingsboard database 
Instructions listed below will help you to install PostgreSQL.
# install **wget** if not already installed:
sudo apt install -y wget

# import the repository signing key:
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# add repository contents to your system:
RELEASE=$(lsb_release -cs)
echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | sudo tee  /etc/apt/sources.list.d/pgdg.list

# install and launch the postgresql service:
sudo apt update
sudo apt -y install postgresql-12
sudo service postgresql start
The instructions below will help to set the password for main postgresql user
sudo su - postgres
psql
\password
\q
Then, press “Ctrl+D” to return to main user console and connect to the database to create thingsboard DB:

psql -U postgres -d postgres -h 127.0.0.1 -W
CREATE DATABASE thingsboard;
\q
Once installed, launch the “pgAdmin” software and login as superuser (postgres). and add new server thigsboard 
General : set the name thingsboard 
connection: set the host to 127.0.0.1
                     set the same password and save it
 then see the thingsboard databse 

now i'm facing a new issue in the code source: TransportProtos make errors and i couldn't find the jar or the maven dependency so i would be thankful  if one could help

**Closed** 2022-05-05 20:31 UTC
Labels: bug

**Comment by DanielBustillos** [comment] 2022-07-19 02:00
> Create a ssh key-pair and all things are good. https://jhooq.com/github-permission-denied-publickey/#1-github---how-to-fix-this-issue

This worked for me and should be added to the source installation guide.
