### ISSUE TITLE
[Question] Mixed-up telemetry data

### ISSUE THREAD

**Issue by jwholme2** [thingsboard/thingsboard#3794] opened 2020-12-01 15:37 UTC
**Component**

 * Generic

**Description**
We seem to have issues with telemetry data mixed between devices. Our backend iterates through roughly 100 devices and sends the payloads to an HTTP Integration. This data then goes through a data converter. The backend logs all requests. However, in Thingsboard, there are several instances where the data received did not match what was sent. Are there any known issues that may explain this? Thanks!

**Environment**

 * OS:  name and version
 * ThingsBoard: self-hosted version 3.0.1PE
 * Browser: name and version

**Comment by ashvayka** [comment] 2020-12-03 15:38
Hi @jwholme2 . The most common issue is that your data converter function uses global and not local variables. 
Use,
```javascript
var myVar = 1;
```
instead of 
```javascript
myVar = 1;
```

At least, this is the only possible root cause that I know.

**Comment by ashvayka** [comment] 2020-12-08 20:36
Hi @jwholme2 , I hope my advice helped to solve the issue. Please provide comments. I am planning to close this issue if no comments within 5 days.

**Closed** 2022-08-26 15:38 UTC
Labels: question
