### ISSUE TITLE
[Bug] docker build error

### ISSUE THREAD

**Issue by aiweilwf** [thingsboard/thingsboard#4421] opened 2021-04-16 06:07 UTC
OS: debian 10
Thingsboard:  V3.2.2
Build  command: mvn clear install -Ddockerfile.skip=false
Error:
[INFO]
[ERROR] The command '/bin/sh -c curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -' returned a non-zero code: 255
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ThingsBoard Docker Images 3.2.2:
[INFO]
[INFO] ThingsBoard Docker Images .......................... FAILURE [01:30 min]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:31 min
[INFO] Finished at: 2021-04-16T12:00:17+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (build-docker-tb-postgres-image) on project tb: Could not build image: The command '/bin/sh -c curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -' returned a non-zero code: 255 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (build-docker-tb-postgres-image) on project tb: Could not build image

**Comment by tozhangkai** [comment] 2021-04-21 21:47
Same problem here. This seems to be caused by https://github.com/thingsboard/docker/commit/e2482d2e26b5e6507152255a23b47605cfa8c874, where the base image is changed from`buildpack-deps:buster-scm` to `debian:buster-slim`. `apt-key` refuses to run with the new image as the dependency `gnupg2` is missing. My workaround is to install `gnupg2` in all Dockerfiles where there's call to `apt-key`, but I think this should be fixed in the base image.

**Comment by Ultrazombie** [comment] 2024-05-20 13:05
Closed due to inactivity

**Closed by Ultrazombie** 2024-05-20 13:05 UTC
