### ISSUE TITLE
Get 408 error when send server side RPC call to device

### ISSUE THREAD

**Issue by hguomin** [thingsboard/thingsboard#245] opened 2017-08-11 16:03 UTC
Hi team,

I follow this document: https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api to send server side rpc to device, but always get the 408 error code when sending the http post request, is there any issues in this api call? thanks.

**Comment by ashvayka** [comment] 2017-08-11 16:26
Are you sure that device is listening to this RPC call and sends the response back?
Otherwise, you will get 408. Alternatively, you can use oneway RPC call.

**Comment by ralienpp** [comment] 2017-08-16 15:19
I have observed the same thing. We send a one-way request from Thingsboard 1.3.0, I have checked that the corresponding HTTP header is present `X-Authorization: "Bearer xxxxxxxx.....xxxxx`.

The listening device is subscribed to the corresponding MQTT topic `v1/devices/me/rpc/request/+`. On the client's end, I see no incoming MQTT message at all.

1. Which server-side log can I look into, to get more details about the problem?
2. What other troubleshooting tips do you recommend?

**Comment by aderbas** [comment] 2017-08-16 17:16
Same problem here, I'm using a module Wemos NodeMCU with lua. I send telemetry or atributes like a GPIO status pin, but my module do not receive anything from the broker. 

```
...
m:connect(host, port, function(client) 
   client:subscribe("/v1/devices/me/rpc/request/+", 0, function(client) print("Subscribe OK") end)
   client:publish("v1/devices/me/attributes", att, 0, 0, function(client) print("Data sent") end)
end,
function(client, reason)
   print(reason)
end)
...
```

But the dashboard or RPC API can not reach my device. I tried to see if it was network problem, but in Raspberry Pi works perfectly.

**Comment by ssmaurya** [comment] 2017-08-17 16:29
Check that device is not disconnecting after sending the telemetry or attributes. Device has to be in connected state and should have subscribed to apt topics to receive rpc or shared attributes updates

**Comment by ralienpp** [comment] 2017-08-18 07:44
According to my client-side log, the connection is established and maintained. With `netstat` or `tcpdump` I see that it is indeed the same TCP connection that is being used.

So I am very confident that the transport layer connection is up and stable.

**Comment by hguomin** [comment] 2017-08-18 07:50
@ashvayka Yes, in my case what I used is one-way RPC call and the device is connected to the server, not two-way.

**Comment by ralienpp** [comment] 2017-08-18 08:18
I just ruled out another possible explanation. I was using QoS 2 (exactly once) for my subscription, but the docs say that Thingsboard supports only QoS 0 and 1.

https://thingsboard.io/docs/reference/mqtt-api/#mqtt-basics
> Thingsboard server nodes act as a MQTT Broker that support QoS levels 0 (at most once) and 1 (at least once) and a set of predefined topics.

Well, I can tell you that this behaviour is not related to the QoS settings.

**Comment by ralienpp** [comment] 2017-08-18 09:50
Alright - I got it.

In my code (using `paho` for Python) I used to declare the subscriptions and then connect to the server. This used to work in the past - but now it doesn't.

I adjusted the code such that the subscription is performed *after* the connection was established. In this case, the  RPC call returns status 200.


I am not sure if this is a bug or a feature, but I need to point out that for my entire life I've been declaring the subscriptions beforehand and it worked with other brokers (e.g. Mosquitto and RabbitMQ's MQTT plugin).

**Comment by ssmaurya** [comment] 2017-08-18 18:08
Subcriptions generally should be done after connection, otherwise there will be no way to say if subscription is valid one or not. I think its by design in thingsboard.

**Comment by ashvayka** [comment] 2017-09-14 03:12
This is actually by MQTT design, not a TB specific. Closing this as invalid.

**Closed by ashvayka** 2017-09-14 03:12 UTC

**Comment by mbari** [comment] 2018-02-16 21:56
I have faced the same problem with thingsboard, my device is unable to subscribe and is not receiving rpc messages from thingsboard. I have tested it on mosquito and works fine. I have tested thingsboard with a python script using paho and it works. The sim800l- arduino combo sends a connection request, it is accepted and then it proceedes to subscribe to the rpc topic, this packet is not acknowledged and times out after some time. I thought I had malformed packets but I went ahead and used wireshark and confirmed that the data packets are exactly similar and therefore this could be a bug on the thingsboard implementation. see attached a screenshot of the wireshark vs arduino data packets.

the issue had also been raised 
![packet capture](https://user-images.githubusercontent.com/1671401/36331038-518d01e6-137d-11e8-96cf-cff9fb9d1960.png)
[here](https://github.com/thingsboard/thingsboard/issues/584)

**Comment by ssmaurya** [comment] 2018-02-17 03:24
Try increasing timeout parameter in rpc shell. We had faced similar issue and increasing timeout solved the issue

**Comment by mbari** [comment] 2018-02-18 09:48
@ssmaurya increasing timeout did not help

**Comment by karlp** [comment] 2018-08-01 14:31
I'm still seeing this, with a one way connection, there shouldn't be any reply from the remote device anyway.  Further, the response code 408 is not documented in the swagger-ui.  As best I can tell, this was caused by attempting to subscribt to v1/devices/me/rpc/requests/# instead of /+

At the very least, documented the 408 code would be helpful please.
