### ISSUE TITLE
C# (m2mqtt client) and Server-Side RPC

### ISSUE THREAD

**Issue by mtheolog** [thingsboard/thingsboard#457] opened 2017-11-29 11:33 UTC
Great work! We would like to incorporate TB  to our IoT solutions. Our device is running on Raspberry pi3 (windows 10 iot core) and in order to collaborate with TB we have implemented a C# device app using m2mqtt client library. 
Even though we are successfully sending telemetry data (properly connection with TB's broker and data visualization in a TB dashboard) we are not able to implement Server-Side RPC. The subscription to the "v1/devices/me/rpc/request/+" topic seems to be successfully established but when we are trying to send a command via a Switch Control widget connected to our TB device, we are getting the message 'Device is offline'. No commands is received from our C# device app.

Below is our code.

### using System;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using uPLibrary.Networking.M2Mqtt;
using uPLibrary.Networking.M2Mqtt.Messages;

namespace UWP_Mqtt_Subscriber
{
    class client
    {
        static MqttClient Client;
        public async static Task Start()
        {

            // Create client instance 

            Client = new MqttClient("192.168.10.115"); //Thingsboard broker

            string username = "iAIIRSrGMnt6lYvLZQVE"; 

            string password = ""; //password is always blank
            Client.MqttMsgPublishReceived += client_MqttMsgPublishReceived;

            byte code = Client.Connect(Guid.NewGuid().ToString(), username, password);

            //code 0x00 Connected - Successfully connected to ThingsBoard MQTT server.
            //code 0x04 Connection Refused, bad user name or password - Username is empty.
            //code 0x05 Connection Refused, not authorized - Username contains invalid $ACCESS_TOKEN

            if (code == 0x00)
            {
                Debug.WriteLine("Client connected to Server node!");
            }
            else
            {
                Debug.WriteLine("Connection Refused");
            }
            try
            {
           
                Client.Subscribe(new string[] { "v1/devices/me/rpc/request/+" }, new byte[] { MqttMsgBase.QOS_LEVEL_AT_MOST_ONCE });

                string Topic = "v1/devices/me/telemetry";
                int p = 100;
                int e = 200;
                int ph = 300;
                
                while (true)
                {
                    string jsonData = "{\"power\":" + p.ToString() + "," + "\"energy\":" + e.ToString() + "," + "\"phase\":" + ph.ToString() + "}";

                    // Message to be sent
                    string Message = Convert.ToString("Publish topic" + Topic + "with jsonData" + jsonData);
                    Debug.WriteLine(Message);

                    Client.Publish(Topic, Encoding.UTF8.GetBytes(jsonData));
                    p++;
                    e++;
                    ph++;

                    await Task.Delay(15000);

                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Start: Exception thrown: " + ex.Message);
            }

        }

        static void client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)
        {
            // handle message received 
            Debug.WriteLine("CCCCC");
            Debug.WriteLine(e.Topic);

        }
    }
}

**Comment by mtheolog** [comment] 2017-12-05 07:48
Extra information. We think that the problem might occur because of QoS level definition. As a matter of fact, when we initially tried to publish messages with specific QoS level, no messages sent to TB's broker. Thus we removed the QoS level definition from PUBLISH method, and it works. In case of subscription, this is not permitted by SUBSCRIBED method. We have to define a specific QoS level.  Is any possibility TB broker do not accept subscriptions with QoS?   Please note, that we noticed that the Javascript examples described in TB's documentation do not define any QoS level in both PUBLISH and SUBSCRIBE methods.

**Comment by mbari** [comment] 2018-02-15 11:59
Did you manage to solve this issue? I am also having similar problems. I have however used a python example script  to successfully receive server side rpc messages. See what I wrote  [here](https://github.com/thingsboard/thingsboard/issues/584)

**Comment by mtheolog** [comment] 2018-02-21 10:19
mbari,

I did NOT manage to solve the issue. I have however developed a uwp node.js app which receives rpc messages and forwards them to our C# apps for further processing. When a response is ready, it is forwarded to the node.js app which sends it to TB. What a waiver! Too much effort just for a bug!

**Comment by mbari** [comment] 2018-02-21 10:56
Hello. Great to hear that you worked around it. I guess I will have to do the same for my application. My case may however be complicated because I may have to maintain two tcp connections, one for uploading telemetry and the other for receiving rpc, how did you ensure that the app received the rpc that were to go to your application? Do they share the access token?

**Comment by vparomskiy** [comment] 2019-02-07 16:35
looks like this thread not active anymore. Maybe we can close it?

**Comment by rgarciasatic** [comment] 2019-03-31 18:18
Just add: 

Client.Publish(Topic, Encoding.UTF8.GetBytes(jsonData),MqttMsgBase.QOS_LEVEL_AT_MOST_ONCE, false);

Will get telemetry data...

**Comment by koen-lee** [comment] 2020-01-30 19:11
Issue https://github.com/thingsboard/thingsboard/issues/1668 might be related.
The cause is the Thingsboard broker sending a noncompliant? subscription response, causing the client to abort the connection.

**Comment by nguyenanhgiau** [comment] 2020-03-12 06:25
Hi https://github.com/mtheolog,
I got it.
I think you should use MQTTnet.
Good luck!

class Program
    {
        static async void Test2() {
            string clientId = Guid.NewGuid().ToString();
            var options = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(new MqttClientOptionsBuilder()
                    .WithClientId(clientId)
                    .WithTcpServer("ip_your_thingsboard")
                    .WithCredentials("your_token", "")
                    .Build())
                .Build();

            var mqttClient = new MqttFactory().CreateManagedMqttClient();
            await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("v1/devices/me/attributes").Build());
            mqttClient.UseApplicationMessageReceivedHandler(e => {
                Console.WriteLine("============== received");
                Console.WriteLine(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
            });
            await mqttClient.StartAsync(options);
        }
        static void Main(string[] args) {
            Test2();
            Console.ReadLine();
        }
    }

**Comment by Ultrazombie** [comment] 2022-01-25 17:05
Hello @mtheolog, 
Did the messages above help you?
Do you still have a problem?

**Closed** 2022-02-01 16:53 UTC
