### ISSUE TITLE
ERROR: duplicate key value violates unique constraint "ts_kv_unq_key"

### ISSUE THREAD

**Issue by marohds** [thingsboard/thingsboard#272] opened 2017-09-01 15:26 UTC
Service stopped after error:
ERROR: duplicate key value violates unique constraint "ts_kv_unq_key"

I'm using demo template with PostgreSQL.

Seems some client is pushing same event twice, and Thingsboard is trying to save it anyway.

¿Is there some validation routine to avoid this kind of problem?

Thanks!

**Comment by ashvayka** [comment] 2017-09-03 07:49
@marohds we will take a look

**Comment by mp-loki** [comment] 2017-09-15 00:36
Hi @marohds
does the error still persist? 
Thingsboard DAO layer uses saveOrUpdate when writing objects to the PostgreSQL database (standard Spring Data JPA functionality), so the same event sent twice should not be a problem. 
I have tried a couple of scenarios to simulate this case but it went smoothly for me, so I could not reproduce it. 

Could you please share some more details about your case?

**Comment by mp-loki** [comment] 2017-11-29 02:55
Fixed in main branch
https://github.com/thingsboard/thingsboard/pull/451

**Closed by mp-loki** 2017-11-29 02:55 UTC
