### ISSUE TITLE
Server side attribute not autogenerated using gateway

### ISSUE THREAD

**Issue by marcozanghi** [thingsboard/thingsboard#827] opened 2018-06-01 12:16 UTC
The following server side attributes are not autogenerated when device is connected throught the gateway. 
Any solution?
![image](https://user-images.githubusercontent.com/1820624/40840306-5d1cd984-65a6-11e8-9f95-90f0793cbd51.png)

**Comment by ashvayka** [comment] 2018-06-03 22:20
@mp-loki This is an about the new feature. It should work automatically, disregarding gateway connection or direct connection.

**Comment by ashvayka** [comment] 2018-06-03 22:32
@marcozanghi I have detected the root cause of the issue and it will be fixed in v2.0.1

**Comment by marcozanghi** [comment] 2018-06-04 19:42
@ashvayka could you give me any details ? I’ll try to contribute for a solution ! Thanks

**Comment by vparomskiy** [comment] 2018-06-12 09:06
Thingsboard 2.0.2 already released

**Closed by vparomskiy** 2018-06-12 09:06 UTC
