### ISSUE TITLE
Get Devices by DeviceType with REST API

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#2934] opened 2020-06-10 11:04 UTC
Hi there,

I try to get all devices by DeviceType with the REST API. Therefore I use FindByQuery, but it don't work.

JSON: { "deviceTypes" : [ "DeviceTypeName" ] }
I post this JSON to BASEURL/api/devices

The response show me this:
<Response [404]>
{"status":404,"message":"Requested item wasn't found!","errorCode":32,"timestamp":"2020-06-10T10:56:25.417+0000","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}

Thanks in advance

 * ThingsBoard: 2.5.1 PE

**Comment by Backdraft007** [comment] 2020-07-01 10:32
Nobody an idea?

**Comment by sonychoudhary** [comment] 2020-11-11 10:28
did it worked for anybody @ashvayka i am facing this issue I want to get list of devices based on device type
![Capture](https://user-images.githubusercontent.com/42209904/98800633-af21e480-2436-11eb-9841-2694b4b27ac9.PNG)
![d](https://user-images.githubusercontent.com/42209904/98800642-b0531180-2436-11eb-8212-44a22783b463.PNG)

**Comment by sonychoudhary** [comment] 2020-11-12 05:30
Duplicate of #3706

**Comment by Ultrazombie** [comment] 2024-05-24 10:46
Closed due to inactivity

**Closed by Ultrazombie** 2024-05-24 10:46 UTC
Labels: question
