### ISSUE TITLE
[Bug] Auth0 (and perhaps other 0Auth providers) - logging out does not clear session

### ISSUE THREAD

**Issue by jskillen** [thingsboard/thingsboard#3513] opened 2020-09-23 21:58 UTC
**Describe the bug**
This occurs when Auth0 is implemented. When a user has successfully logged in using Auth0 and they log out the Auth0 session is not cleared; the user is able to immediately log in again without being challenged for credentials.

**Your Server Environment**

* own setup
  * Cloud deployment
  * ThingsBoard Version 3.1.1
  * Ubuntu 20

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Mac Catalina v 10.15.6
* Browser: Chrome version 85.0.4183.83

**Smartphone (please complete the following information):**
* n/a

**Your Device**

* Connectivity
  * n/a

**To Reproduce**
1. With Auth0 implemented in the application, log in to Thingsboard.
2. Log out.
3. Log in again; click the 'Log in with Auth0' button.
4. Observe that you are not challenged for credentials.

**Expected behavior**
I would expect that the Auth0 implementation would ask for credentials after the user has successfully logged out.

**Additional context**
https://auth0.com/docs/quickstart/webapp/java-spring-boot#add-logout-to-your-application

**Comment by andrew355** [comment] 2020-09-25 12:33
We've implemented Auth0 using the TB 3.1.1 PE OAuth2 integration and experience the same issue.

I think the problem is that there's no way to specify the "https://my_auth0_domain/v2/logout" logout endpoint (referred to in the "Additional context" above) in the TB configuration. It's this call that clears the Auth0 SSO cookie: https://auth0.com/docs/logout/log-users-out-of-auth0
and which would force the Auth0 login dialog to appear again.

That logout endpoint is specific to Auth0, rather than to OAuth2 providers in general, which maybe why TB don't implement it. If Google or Facebook were being used in a TB OAuth2 integration then you probably wouldn't want to log the current user out of Google/Facebook when you logged out of TB.

We'd like the issue fixed too, as the user has a weird experience with a TB Auth0 integration when they logout, since they don't need to log back in again to access the application. Finding a way to call that Auth0 logout endpoint will be the key.

**Comment by Ayomi-gh** [comment] 2021-06-20 12:01
I have written a fix for this and submitted a pull request. In short by adding the prompt login paramter to the autorize request to the Oauth2 provider, we can force the user to login. This can theretically be bypassed by a man in the middle but is a huge improvement. 

https://github.com/thingsboard/thingsboard/pull/4693

**Comment by IoTThinks** [comment] 2023-03-30 06:06
So is there any workaround for this issue till now?
I have the same issue with Auth0 and PE 3.4.4.

1. With Auth0 implemented in the application, log in to Thingsboard.
2. Log out.
3. Log in again; click the 'Log in with Auth0' button.
4. Observe that you are not challenged for credentials.

**Comment by maghibus** [comment] 2023-07-28 09:47
I have the same problem with Keycloak and CE 3.5.1

**Comment by mykhailokornieiev** [comment] 2024-11-18 13:48
Hi
We already have such feature request in our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Closed by mykhailokornieiev** 2024-11-18 13:48 UTC
Labels: feature
