### ISSUE TITLE
Migration 2.4.3 to 2.5 in Amazon RDS, Permission Issue?

### ISSUE THREAD

**Issue by russelmahmud** [thingsboard/thingsboard#2880] opened 2020-05-29 13:46 UTC
I am getting this error while migrating in Amazon RDS.

Failed to execute query: call insert_into_ts_kv('/tmp/ts_kv2267233513583762561/ts_kv.sql') due to: ERROR: must be superuser or a member of the pg_write_server_files role to COPY to a file
Hint: Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.
I couldn't find anyway to give permission pg_write_server_files for the master user of RDS instance. Has anyone faced the same problem?

**Comment by wadimklincov** [comment] 2020-05-29 15:22
I had the exact same issue. And retrying the upgrade only led to endless loops of #2767.:(

**Comment by russelmahmud** [comment] 2020-05-29 16:30
> I had the exact same issue. And retrying the upgrade only led to endless loops of #2767.:(

Have you solved it? Have you faced same problem in Amazon RDS (Postgresql)?

**Comment by wadimklincov** [comment] 2020-05-29 16:37
> Have you solved it? Have you faced same problem in Amazon RDS (Postgresql)?

Yes I've had the exact same issue with RDS (after upgrading from 9 to 11), but I wasn't able to solve either issue.

**Comment by ashvayka** [comment] 2020-06-01 12:39
This is fixed in 2.5.1 that we plan to release today. The problem is that AWS RDS DB user can't use "COPY" command. In 2.5.1 we have updated upgrade script and will fallback to use plan inserts. This is slower but works everywhere.

**Closed by ashvayka** 2020-06-01 12:39 UTC
Labels: question
