### ISSUE TITLE
RPC settings in Status LED is not working.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#348] opened 2017-10-13 16:16 UTC
While I was playing around with the Led Indicator control widget, I realised that the `Check device status method` field in advanced settings is not working.

No matter what I put to this field, the widget will always RPC my device the method `checkStatus`.

**Comment by ikulikov** [comment] 2017-10-16 08:11
I'll double check.

**Comment by ikulikov** [comment] 2017-10-16 12:58
Yes, I was able to reproduce the issue. The problem was in incorrect settings parameter name. The fix currently in the master branch and will be included in release v.1.3.1.

**Closed by ikulikov** 2017-10-16 12:58 UTC
