### ISSUE TITLE
MQTT connection lost when run 10 minutes in TB 2.4.0

### ISSUE THREAD

**Issue by tianguochun** [thingsboard/thingsboard#1898] opened 2019-08-01 03:32 UTC
MQTT connection lost when run 10 minutes in TB 2.4.0，but not this issue in TB 2.3.1

**Comment by madper** [comment] 2019-08-01 04:15
The master branch already fixed the issue. I confirmed it.

**Comment by pingchesu** [comment] 2019-08-08 02:36
@madper 
> The master branch already fixed the issue. I confirmed it.

I faced the same mqtt issue!!
However, where can I find the related mqtt fixed code?
Thanks for answering!!

**Comment by madper** [comment] 2019-08-08 03:01
> @madper
> 
> > The master branch already fixed the issue. I confirmed it.
> 
> I faced the same mqtt issue!!
> However, where can I find the related mqtt fixed code?
> Thanks for answering!!

IIRC, Should be this one: https://github.com/thingsboard/thingsboard/commit/4e71935d27ca12d6ffc630d2175e166d9bcbc4ad

**Comment by pingchesu** [comment] 2019-08-08 06:32
> > @madper
> > > The master branch already fixed the issue. I confirmed it.
> > 
> > 
> > I faced the same mqtt issue!!
> > However, where can I find the related mqtt fixed code?
> > Thanks for answering!!
> 
> IIRC, Should be this one: [4e71935](https://github.com/thingsboard/thingsboard/commit/4e71935d27ca12d6ffc630d2175e166d9bcbc4ad)

Thanks for help!!

**Comment by shanevanj** [comment] 2019-08-17 06:22
> > @madper
> > > The master branch already fixed the issue. I confirmed it.
> > 
> > 
> > I faced the same mqtt issue!!
> > However, where can I find the related mqtt fixed code?
> > Thanks for answering!!
> 
> IIRC, Should be this one: [4e71935](https://github.com/thingsboard/thingsboard/commit/4e71935d27ca12d6ffc630d2175e166d9bcbc4ad)

Is there a downloadable .deb for this fix yet ?

**Comment by shanevanj** [comment] 2019-09-03 15:21
> The master branch already fixed the issue. I confirmed it.

How do you install this fix? I have an existing 2.4.0 PE - can it be Patched?

**Comment by madper** [comment] 2019-09-04 10:37
@shanevanj  Sorry for the late reply.
I have totally no idea about PE. There is no deb package yet. I built an java-jar weeks ago.

**Comment by IoTThinks** [comment] 2019-11-02 09:38
The connection lost issue is confirmed to be fixed in TB 2.4.1 (CE).
I had the MQTT session drops after around 7 minutes in TB 2.4.0 (CE). Upgrading fixed the issue.

Thanks for the patch. (y)

**Comment by Karabiy** [comment] 2020-06-30 08:10
the issue seems to be outdated

**Closed by Karabiy** 2020-06-30 08:10 UTC
