### ISSUE TITLE
NullPointerException after upgrading ThingBoard from 3.6 to 3.7

### ISSUE THREAD

**Issue by synetalsolutions** [thingsboard/thingsboard#11030] opened 2024-06-18 05:45 UTC
Describe the Bug:
After upgrading ThingBoard from version 3.6 to 3.7, a NullPointerException occurs related to caching functionality.

Steps to Reproduce:
1. Upgrade ThingBoard from version 3.6 to 3.7.
2. Access any functionality that involves caching.
3. Observe the NullPointerException in the logs.

Expected Behavior:
Caching should function correctly without any NullPointerExceptions after the upgrade.

Actual Behavior:
A NullPointerException is thrown with the following stack trace:
```
NullPointerException: Cannot invoke "org.springframework.cache.Cache.evict(Object)" because the return value of "org.springframework.cache.CacheManager.getCache(String)" is null
```

Additional Information:
- ThingBoard version before upgrade: 3.6
- ThingBoard version after upgrade: 3.7
- Java version: openjdk 17.0.11 2024-04-16 LTS
- Operating System: Almalinux 8

Screenshots:

![image](https://github.com/thingsboard/thingsboard/assets/32237609/ac9bec71-bcac-4c82-865a-b8be11879530)

Possible Solution:
Investigate why `org.springframework.cache.CacheManager.getCache(String)` is returning null after the upgrade. Ensure that caching configurations are correctly migrated or adjusted for ThingBoard 3.7.

**Comment by ViacheslavKlimov** [comment] 2024-06-18 09:33
Have you properly updated the thingsboard.yml? See the similar issue: https://github.com/thingsboard/thingsboard/issues/10931

**Comment by synetalsolutions** [comment] 2024-06-18 10:44
After uninstalling and reinstalling it start working.

Thanks for your support.

**Comment by avipala** [comment] 2024-08-08 19:52
It happened to me as well, same sequence, after upgrading to 3.7
It worked - but after first reset, got the same null error

**Comment by AndreasHansson73** [comment] 2024-08-18 15:02
I  got the same error when upgrading from 3.6.4 to 3.7.0 using the docker image thingsboard/tb-postgres .  I tried the solution mentioned above changing the thingsboard.yml file but it didn't help.

**Comment by AndreasHansson73** [comment] 2024-08-18 19:52
I upgraded thingsboard from 3.6.4 to 3.7.0 and now I have the same problem. I use the docker image thingsboard/tb-postgres. I use the instructions on this page https://hub.docker.com/r/thingsboard/tb-postgres.
This bus should be easy to reproduce. Just initialize a new system with thingsboard/tb-postgres:3.6.4 and then use the script to upgrade to 3.7.0.

**Comment by ianfsagp** [comment] 2024-08-21 12:28
I now have same issue, yaml file is correct but get the same null pointer error when trying to login - any other pointers ? Uninstalling is not an option !

**Comment by ViacheslavKlimov** [comment] 2024-08-22 10:40
Please set HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE env variable to "true" and reproduce the issue. 
The error stacktrace will appear in the logs. Please send it and also attach the current version of your thingsboard.yml.

**Comment by AndreasHansson73** [comment] 2024-08-24 16:06
Is this of any help?

`java.lang.NullPointerException: Cannot invoke "org.springframework.cache.Cache.evict(Object)" because the return value of "org.springframework.cache.CacheManager.getCache(String)" is null
mytb_1  |       at org.thingsboard.server.cache.CaffeineTbTransactionalCache.doEvict(CaffeineTbTransactionalCache.java:117)
mytb_1  |       at org.thingsboard.server.cache.CaffeineTbTransactionalCache.lambda$evict$0(CaffeineTbTransactionalCache.java:89)
mytb_1  |       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
mytb_1  |       at org.thingsboard.server.cache.CaffeineTbTransactionalCache.evict(CaffeineTbTransactionalCache.java:87)
mytb_1  |       at org.thingsboard.server.dao.user.UserServiceImpl.handleEvictEvent(UserServiceImpl.java:116)
mytb_1  |       at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:190)
mytb_1  |       at org.thingsboard.server.dao.user.UserServiceImpl.resetFailedLoginAttempts(UserServiceImpl.java:432)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
mytb_1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytb_1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
mytb_1  |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
mytb_1  |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:713)
mytb_1  |       at org.thingsboard.server.dao.user.UserServiceImpl$$SpringCGLIB$$0.resetFailedLoginAttempts(<generated>)
mytb_1  |       at org.thingsboard.server.service.security.system.DefaultSystemSecurityService.validateUserCredentials(DefaultSystemSecurityService.java:154)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
mytb_1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytb_1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
mytb_1  |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
mytb_1  |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:713)
mytb_1  |       at org.thingsboard.server.service.security.system.DefaultSystemSecurityService$$SpringCGLIB$$0.validateUserCredentials(<generated>)
mytb_1  |       at org.thingsboard.server.service.security.auth.rest.RestAuthenticationProvider.authenticateByUsernameAndPassword(RestAuthenticationProvider.java:129)
mytb_1  |       at org.thingsboard.server.service.security.auth.rest.RestAuthenticationProvider.authenticate(RestAuthenticationProvider.java:101)
mytb_1  |       at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
mytb_1  |       at org.thingsboard.server.service.security.auth.rest.RestLoginProcessingFilter.attemptAuthentication(RestLoginProcessingFilter.java:81)
mytb_1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231)
mytb_1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
mytb_1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:181)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
mytb_1  |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
mytb_1  |       at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
mytb_1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
mytb_1  |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
mytb_1  |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
mytb_1  |       at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
mytb_1  |       at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
mytb_1  |       at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
mytb_1  |       at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
mytb_1  |       at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
mytb_1  |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
mytb_1  |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
mytb_1  |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
mytb_1  |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
mytb_1  |       at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
mytb_1  |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
mytb_1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
mytb_1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
mytb_1  |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
mytb_1  |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
mytb_1  |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
mytb_1  |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
mytb_1  |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
mytb_1  |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
mytb_1  |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
mytb_1  |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
mytb_1  |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
mytb_1  |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
mytb_1  |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
mytb_1  |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
mytb_1  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
mytb_1  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
mytb_1  |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
mytb_1  |       at java.base/java.lang.Thread.run(Thread.java:840)
`

**Comment by AndreasHansson73** [comment] 2024-08-24 16:23
It turned out I hade some error the one of the config files. After setting default value it seem to work!

**Comment by ViacheslavKlimov** [comment] 2024-08-27 09:46
@ianfsagp, what about your issue?

**Comment by ianfsagp** [comment] 2024-08-27 09:49
I had to take a fresh thingsboard.yml file from a clean install of 3.7 and overwrite the old 3.6 version on the broken machine.  This has now fixed the problem but made some of my widgets inoperable !!!  I’ve now started from scratch again in a cleanly installed version 3.7.

In future I will NOT perform an upgrade as I have no confidence in them !!





From: Viacheslav Klimov ***@***.***>
Date: Tuesday, 27 August 2024 at 10:46
To: thingsboard/thingsboard ***@***.***>
Cc: Ian Forde-Smith ***@***.***>, Mention ***@***.***>
Subject: Re: [thingsboard/thingsboard] NullPointerException after upgrading ThingBoard from 3.6 to 3.7 (Issue #11030)

@ianfsagp<https://github.com/ianfsagp>, what about your issue?

**Closed** 2024-10-03 11:23 UTC
Labels: bug, unconfirmed
