### ISSUE TITLE
Thingsboard html heatmap

### ISSUE THREAD

**Issue by Eliboy633** [thingsboard/thingsboard#10940] opened 2024-06-06 09:08 UTC
I am trying to create a heatmap in thingsboard but i can't get it to work. I tried doing it with a html card but got stuck with the problem that I should need javascript. I found out that i can make custom widgets where i can use javascript but still can't get a visual of a heatmap. Can someone help me with making a heatmap?

**Comment by devaskim** [comment] 2024-06-06 10:41
https://github.com/thingsboard/thingsboard/issues/10817

**Comment by Eliboy633** [comment] 2024-06-06 13:28
This is my code, do you see any mistakes why it doesn't work?
JS: 
self.onInit = function() {
    self.ctx.map = new TbMapWidgetV2('openstreet-map', false, self.ctx);
    self.markers = []; // Houd een lijst bij van alle markers
    
    // Voeg initiale markers toe
    if (self.ctx.data) {
        self.addMarkers(self.ctx.data);
    }
}

self.onDataUpdated = function() {
    // Voeg nieuwe markers toe wanneer de gegevens worden bijgewerkt
    if (self.ctx.data) {
        self.addMarkers(self.ctx.data);
    }
}

self.addMarkers = function(data) {
    data.forEach(function(item) {
        if (item.latitude !== undefined && item.longitude !== undefined) {
            var color = getColorBasedOnQuantity(item.product_hoeveelheid); // Aangepast naar item.product_hoeveelheid
            var marker = L.marker([item.latitude, item.longitude], {
                icon: L.divIcon({
                    className: 'custom-marker marker-' + color,
                    html: '<div class="marker-inner"></div>'
                })
            }).addTo(self.ctx.map);

            if (item.product_hoeveelheid !== undefined) { // Aangepast naar item.product_hoeveelheid
                marker.bindTooltip('Product Hoeveelheid: ' + item.product_hoeveelheid); // Aangepast naar item.product_hoeveelheid
            }

            self.markers.push(marker); // Voeg de nieuwe marker toe aan de lijst
        }
    });
}

self.onResize = function() {
    if (!self.ctx.map) {
        console.error("Map is not initialized.");
        return;
    }
    self.ctx.map.resize();
}

self.actionSources = function() {
    return TbMapWidgetV2.actionSources();
}

self.onDestroy = function() {
    if (self.ctx.map) {
        self.ctx.map.destroy();
    }
}

self.typeParameters = function() {
    return {
        hasDataPageLink: true
    };
}

function getColorBasedOnQuantity(product_hoeveelheid) {
    if (product_hoeveelheid > 100) {
        return 'green';
    } else if (product_hoeveelheid > 50) {
        return 'orange';
    } else {
        return 'red';
    }
}

CSS:

.marker-red .marker-inner {
    background-color: red;
    width: 10px;
    height: 10px;
    border-radius: 50%;
}

.marker-orange .marker-inner {
    background-color: orange;
    width: 10px;
    height: 10px;
    border-radius: 50%;
}

.marker-green .marker-inner {
    background-color: green;
    width: 10px;
    height: 10px;
    border-radius: 50%;
}

.leaflet-zoom-box {
    z-index: 9;
}

.leaflet-pane {
    z-index: 4;
}

.leaflet-tile-pane {
    z-index: 2;
}

.leaflet-overlay-pane {
    z-index: 4;
}

.leaflet-shadow-pane {
    z-index: 5;
}

.leaflet-marker-pane {
    z-index: 6;
}

.leaflet-tooltip-pane {
    z-index: 7;
}

.leaflet-popup-pane {
    z-index: 8;
}

.leaflet-map-pane canvas {
    z-index: 1;
}

.leaflet-map-pane svg {
    z-index: 2;
}

.leaflet-control {
    z-index: 9;
}

.leaflet-top,
.leaflet-bottom {
    z-index: 11;
}

.tb-marker-label {
    border: none;
    background: none;
    box-shadow: none;
}

.tb-marker-label:before {
    border: none;
    background: none;
}

**Comment by Ultrazombie** [comment] 2024-06-10 14:59
Closed due to duplicate of https://github.com/thingsboard/thingsboard/issues/10817
@Eliboy633 Keep in touch in the ticket above.

**Closed by Ultrazombie** 2024-06-10 14:59 UTC
Labels: question
