### ISSUE TITLE
[Bug] Unexpected Loading Time when using Custom Actions (with HTML) and Read-Only Permissions

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#4608] opened 2021-05-20 13:40 UTC
**Bug Description**
While logged in with a user having Read-Only Permissions, clicking on Edit with Custom Actions (with HTML) leads to long loading times. First "Permission Denied" ist displayed, which is correctly. But the progress bar keeps moving, even after closing the processing continues, leading to a not responsible Dashboard (e.g. other Action Buttons are not clickable anymore).

![CPT2105201548-1000x495](https://user-images.githubusercontent.com/25298332/118990766-76357000-b983-11eb-8fda-d19b80066d8d.gif)

Only solution to stop the loading:

1. log out
2. reload login page
3. login again

**Server Environment**
 * ThingsBoard Version 3.2.2

**Expected behavior**
No loading times at all. Behavior is excepted the same as for the Device Admin Widget (Default Edit Action). In that case everything is working fine.

**Screenshots**

Permission Denied & Loading starts:
![image](https://user-images.githubusercontent.com/25298332/118986588-c9a5bf00-b97f-11eb-8020-07ea3b0f447b.png)

Loading still present after closing the message window:
![image](https://user-images.githubusercontent.com/25298332/118986799-f0fc8c00-b97f-11eb-9202-ef2cca11cf9d.png)

Icons not clickable anymore (after closing edit dialog):
![image](https://user-images.githubusercontent.com/25298332/118987932-07efae00-b981-11eb-9793-591669810c04.png)

**Comment by LeoMorgan113** [comment] 2021-06-01 12:57
Hi @mde2017,

As I understand, you use custom action "Edit" with your own code, don't you?
If yes, could you please provide your code?

Because with default "Edit" everything works fine and I don't get unexpected behavior described by you.
There only "Permission Denied" and no loading line.

**Comment by mde2017** [comment] 2021-06-01 13:14
Hi @LeoMorgan113,

thanks for your reply.

Yes, the default "Edit" is working fine. The mentioned behavior is observed with a Custom Action (with HTML template). Where I just used the prefilled examples for edit operation, as described in the following video tutorial:
https://www.youtube.com/watch?v=4qSSbqXntEQ

No further changes were made in the code. I can still provide the code if helpful.

**Comment by LeoMorgan113** [comment] 2021-06-01 13:17
@mde2017 yes, could you please attach the code?

**Comment by mde2017** [comment] 2021-06-01 13:22
@LeoMorgan113 attached the code for each section

[javascript_section.txt](https://github.com/thingsboard/thingsboard/files/6576510/javascript_section.txt)
[html_section.txt](https://github.com/thingsboard/thingsboard/files/6576511/html_section.txt)

**Comment by LeoMorgan113** [comment] 2021-06-01 13:46
Yeah, it's really an issue.
So I added your appeal to the backlog(PROD-1001), so it will be reviewed by our developers, but I can not provide you with an exact time frame on this.
I'll close the issue.
@mde2017 thanks for your participation.

**Closed by LeoMorgan113** 2021-06-01 13:46 UTC
Labels: bug
