### ISSUE TITLE
Displaying Future Timestamps with Configurable Time Window

### ISSUE THREAD

**Issue by HannesPiadeno** [thingsboard/thingsboard#11988] opened 2024-11-04 05:57 UTC
A significant part of our daily operations involves working with data for the upcoming days, primarily D+1 and D+2.

Current Behavior: We’ve tried the "Interval" Time Window setting and attempted to use the Trendz Analytics Package; however, neither solution fully meets our requirements. The current setup lacks the flexibility needed to effectively view and work with future timestamps.

Feature Request: Ideally, we would like to have the following functionality:

The ability to select the last 'x' days.
The option to add a parameter for the next 'y' days, allowing us to customize the display window to include future dates.

Questions: Are there any current settings or configurations within TB that support this feature? If not, would it be possible to consider this as an enhancement request?

Thank you.

**Comment by IrynaKh1204** [comment] 2024-11-05 12:19
Hi,
We understand the importance of having flexible date settings for working with future timestamps. Currently, there isn’t a specific setting in Trendz that fully supports the functionality you're looking for.

However, we have improvements planned for the Trendz date picker in upcoming releases, which should offer enhanced flexibility for viewing and working with custom date ranges, including future dates.

**Comment by HannesPiadeno** [comment] 2024-11-18 09:00
Hello,
Thank you for the prompt response.
Is it possible to configure support for future timestamps directly in Thingsboard? How could this functionality be implemented using the widget editor?

**Comment by mykhailokornieiev** [comment] 2024-12-05 12:01
Hi. By design, future timestamps cannot be displayed on any Thingsboard widget. Such a feature won't be implemented as default Thingsboard functionality. As @IrynaKh1204 mentioned, there are plans to add such a feature to Trendz.

**Comment by mykhailokornieiev** [comment] 2024-12-12 11:25
Closed due to inactivity

**Closed by mykhailokornieiev** 2024-12-12 11:25 UTC
Labels: feature
