### ISSUE TITLE
Trendz Calculated fields multiple Y Axis issue 

### ISSUE THREAD

**Issue by ChrisEvisi** [thingsboard/thingsboard#7695] opened 2022-11-28 22:24 UTC
**Describe the bug**
When adding multiple Calculated fields in Trendz with different units, only a single Y Axis scale is displayed.  The other Calculated fields unit scales are hidden.  

**Your Server Environment**

* AWS EC2 
* ThingsBoard 3.4.1 PE

**Expected behavior**
Both Calculated and Non-calculated fields should display their Y-Axis units scale.  

**Screenshots**
Multiple Y Axis scales are shown when using non-calculated fields as below
![image](https://user-images.githubusercontent.com/66198901/204393317-52f8c460-f7ec-4060-83bf-2b0da7e108fc.png)

the Non-calculated fields chart shows multiple Y Axis scales
![image](https://user-images.githubusercontent.com/66198901/204393442-83f9cb6f-5258-4462-987c-d46974647322.png)

Thanks for any assistance with this.

**Comment by oleksandr-kupenko** [comment] 2022-11-29 20:04
Please check what version of the program do you have? You can find it in the settings in the bottom right corner.
In the latest version 1.92 I was not able to reproduce the problem.
![multiple_fields](https://user-images.githubusercontent.com/53411825/204635035-7326a289-7738-4b71-8bbf-4ef66865e534.png)


![trendz_setings](https://user-images.githubusercontent.com/53411825/204636409-cd40205b-15f9-46a6-ae06-e5257a63c220.png)

**Comment by ChrisEvisi** [comment] 2022-11-29 20:17
Hi Oleksandr,
Thanks for your fast reply.  
We are using 1.9.2 also
I got the same result as you described above also when I use a mix of calculated and non-calculated fields.  But when I only used calculated fields only a single Y Axis scale was displayed.  
![image](https://user-images.githubusercontent.com/66198901/204638884-f6c8d53f-0692-4abd-88f0-6a7e0dbda80c.png)

**Comment by oleksandr-kupenko** [comment] 2022-11-29 20:19
Yes, you are absolutely right. Sorry. The problem will be solved very soon.

**Comment by ChrisEvisi** [comment] 2022-11-29 20:26
great,  thanks for ultra fast reply.

**Comment by oleksandr-kupenko** [comment] 2022-12-01 21:57
Hi Chris,
I want to inform you that this problem is fixed in the new release. You can [update your program to version 1.9.2](https://thingsboard.io/docs/trendz/install/installation-options/). 
It's important to use different names (labels) for these calculated fields.

![fixed_calculated_multiple_fields](https://user-images.githubusercontent.com/53411825/205166812-a58b3008-ba43-4d38-80f3-bf648e2bc60f.png). 

But if this is not critical, then I would recommend waiting just a few more days. Minor additional changes may be made. But they are very minor and do not have any effect on the final appearance of the visualizations.

Really thank you for your feedback. It really helps to find and fix problems.

**Comment by ChrisEvisi** [comment] 2022-12-02 06:17
Thanks very much Aleksandr,

 

We will wait a few days and then upgrade with any near future changes.  

 

Very best wishes

Nga mihi nui  

 

Chris Olson

**Closed** 2022-12-03 01:30 UTC
Labels: bug
