### ISSUE TITLE
build from source failed .... 

### ISSUE THREAD

**Issue by colognebroker** [thingsboard/thingsboard#1553] opened 2019-03-14 18:51 UTC
during install it fails to install netty-mqtt, would be nice if basics could run
running 2.3.1

[INFO] Thingsboard ........................................ SUCCESS [  4.711 s]
[INFO] Netty MQTT Client .................................. FAILURE [  2.514 s]
[INFO] Thingsboard Server Commons ......................... SKIPPED

[INFO] Final Memory: 26M/505M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project netty-mqtt: Fatal error compiling: directory not found: /home/ufa/thingsboard/netty-mqtt/target/classes -> [Help 1

**Comment by colognebroker** [comment] 2019-03-14 20:28
solved

**Comment by mfalkvidd** [comment] 2019-03-15 08:28
@colognebroker would you mind sharing how it was solved, in case someone else has a similar problem in the future and finds this github issue?

**Comment by colognebroker** [comment] 2019-03-15 11:55
i startet mvn with sudo, after rm .* hidden directorys and start again everything was ok

**Comment by demirizZz** [comment] 2019-05-15 11:26
What is your run command?

**Comment by GirishVC86** [comment] 2019-08-13 17:14
@colognebroker can you please specify the steps including commands for resolving this error.

**Comment by marianodo** [comment] 2019-11-08 14:27
I had the same issue but the cause was other. I tried to compile master branch with java 11. When I realized I did the following:
- sudo update-alternatives --config java
- Select Java 8
- Remove thingboard folder
- Clone again
- Checkout to release-2.4
- mvn clean install (without sudo)

That worked for me

**Comment by MirkoUgoliniDev** [comment] 2020-04-18 15:40
Hello all,

I got the same problem.

I followes this  suggestion:

Deleting the .m2 folder in the user/USERNAME/ directory as well as making sure that the JAVA_HOME

But I did not solve the problem

Ubuntu 64 bit

**Comment by periatrubikx** [comment] 2021-02-14 07:17
I ran into this issue after i took an update from master. I noticed, the maven-compiler-plugin is now looking at Java 11 instead of 8 as before. I updated my local java version to be 11 and it the code would compile/build fine. Hope this helps.

**Comment by Ultrazombie** [comment] 2024-05-28 07:25
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Closed by Ultrazombie** 2024-05-28 07:25 UTC
