### ISSUE TITLE
Thingsboard does not startup due to circular dependencies when disabling Swagger-UI on TB 3.7.0

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#11145] opened 2024-07-04 07:41 UTC
When trying to disable the Swagger UI by setting

- "springdoc.api-docs.enabled" to "false"

the thingsboard service does not start up complaining about circular dependencies:

![image](https://github.com/thingsboard/thingsboard/assets/11454768/a65ef7a7-a98c-4a3b-93c0-8356c85fba24)

TB-CE 3.7.0 monolith running on Ubuntu 22.04.4.

Any hints how to disable the Swagger-UI?
Thanks!

**Comment by mykhailokornieiev** [comment] 2024-07-04 14:17
Hi
You need to specify this parameter `export SWAGGER_ENABLED=false` in `/etc/thingsboard/conf/thingsboard.conf` file and restart service with `sudo service thingsboard restart `
https://thingsboard.io/docs/user-guide/install/pe/config/#spring-doc-common-parameters

**Comment by BatListener** [comment] 2024-07-04 14:30
Hi,
Thanks for the swift reply!

Just checked your propsal:
Setting export SWAGGER_ENABLED=false in /etc/thingsboard/conf/thingsboard.conf 
has the same effect as setting the same configuration in the thingsboard.yml-file (as I did before).

In both cases, the thingsboard service fails to start if set the parameter to false.
I got the same circular dependency log entry as described above.

Everything is fine, when set to true. Swagger UI is shown then, of course.

**Comment by mykhailokornieiev** [comment] 2024-07-04 15:14
I've just tested it on a local instance, and indeed, the issue is reproduced. This looks like a bug in a platform - I had already added to our backlog a ticket for a product team (PROD-3967). Once the product team reviews this ticket, we’ll post an update on when this fix for this bug could be delivered or how to disable swagger correctly if there is not enough information in documentation.

**Comment by mykhailokornieiev** [comment] 2024-09-26 14:39
Hi. This issue already fixed in the upcoming release.

**Closed by mykhailokornieiev** 2024-09-26 14:39 UTC
Labels: bug, confirmed
