### ISSUE TITLE
[Bug] - rulechain node fails randomly (No such function invokeInternal_...)

### ISSUE THREAD

**Issue by gabrielpanasco** [thingsboard/thingsboard#5182] opened 2021-09-01 20:33 UTC
Packets stop traversing rule engine stopping at a random node inside any random rulechain. All subsequent packets from same or other devices also stop being processed upon reaching problematic node. Resaving (without altering node configuration) the defective node rule chain solves problem at the malfunctioning node, however problem might reappear in following nodes at random (thus stopping - or not - at another rulechain node). *More details at the end.

Using self-hosted Thingsboard instance.
HW: 2vCPUs, 4GB RAM, Hyper-V 
OS: Ubuntu Server 18.04
TB Version: 3.2.0
Using Chrome on Windows latest version

Our devices integrate with Thingsboard using HTTP simple API

To reproduce:
Problem is hard to reproduce reliably, as it seems to happen at random times, on random rulechain nodes.

Additional information:

Thingsboard log shows:

2021-08-25 19:02:18,369 [tb-rule-engine-consumer-23-thread-3] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - Timeout to process [1] messages
2021-08-25 19:02:18,369 [tb-rule-engine-consumer-23-thread-3] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [6f695e70-db5d-11eb-81ed-b780fb99ebc9] Timeout to process message: TbMsg(queueName=Main, id=452c2ea1-06b6-4653-be59-e47eacd8a7e2, ts=1629918136367, type=POST_TELEMETRY_REQUEST, originator=65c24900-dd91-11eb-a958-bd98a6dc64bd, metaData=TbMsgMetaData(data={deviceType=default, deviceName=DL-6, ts=1629918000000}), dataType=JSON, data={"prot":3,"sn":241,"s1d1":0.16,"s1d2":31.438000000000002,"vbat":3.439,"lbat":false,"type":"data","rssi":-90,"snr":14.2,"tags":{}}, ruleChainId=16a4ee20-ff7b-11eb-b08f-3f94f7f5da73, ruleNodeId=null, ruleNodeExecCounter=0, callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@69dec46), Last Rule Node: [RuleChain: package_separation_n|RuleNode: NOP(16c21310-ff7b-11eb-b08f-3f94f7f5da73)]
2021-08-25 19:02:18,419 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-2 [Attributes] queueSize [0] totalAdded [1] totalSaved [1] totalFailed [0]
2021-08-25 19:02:18,438 [TB-Scheduling-1] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [1] successfulMsgs = [0] timeoutMsgs = [1] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterations = [0] failedIterations = [1]
2021-08-25 19:02:18,438 [TB-Scheduling-1] INFO  o.t.s.s.queue.TbCoreConsumerStats - Core Stats: totalMsgs = [1] sessionEvents = [0] getAttr = [0] subToAttr = [0] subToRpc = [0] toDevRpc = [0] subInfo = [1] claimDevice = [0] deviceState = [0] subMsgs = [0] coreNfs = [0]
2021-08-25 19:02:18,443 [TB-Scheduling-1] INFO  o.t.server.actors.ActorSystemContext - Rule Engine JS Invoke Stats: requests [1] responses [0] failures [0]
2021-08-25 19:02:21,908 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-2 [TS] queueSize [0] totalAdded [6] totalSaved [6] totalFailed [0]

The same failed packet log message persists at every received device packet until resaving problematic node and rulechain.

In addition, upon enabling debug mode on nodes we get:

java.util.concurrent.ExecutionException: java.lang.NoSuchMethodException: No such function invokeInternal_0f69ac54_3baf_4597_b114_6bd41f7c0522
	at org.thingsboard.server.service.script.AbstractNashornJsInvokeService.lambda$doInvokeFunction$1(AbstractNashornJsInvokeService.java:155)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoSuchMethodException: No such function invokeInternal_0f69ac54_3baf_4597_b114_6bd41f7c0522
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:207)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at org.thingsboard.server.service.script.AbstractNashornJsInvokeService.lambda$doInvokeFunction$1(AbstractNashornJsInvokeService.java:151)
	... 9 more

We tried disabling JS sandbox (USE_LOCAL_JS_SANDBOX=false), however without success.

Sorry for not being able to give clear steps to reproduce the behavior, as the problem occurs quite randomly. 

Any ideas are appreciated.

**Comment by JacksonBowe** [comment] 2021-09-01 21:59
Question. Do these errors appear only in nodes that contain written JS? If so, what does you code look like as an example?

The reason I ask is because I have found with Thingsboard that the following is absolutely going to cause issues.
`// node A`
` x = 'hello'`

`// node B`
`x = 4`
`y = x + 6`

Why will this cause errors? Because for some reason Thingsboard treats all declaration with out `var/let/...` as **global**.

This means that if Node B is getting executed, does x = 4, then anther rule chain message triggers Node A before Node B gets to the next line you will have `y = 'hello' + 4` which will error.

Is it possible that some interaction like this may be causing your problem?

**Comment by gabrielpanasco** [comment] 2021-09-01 22:12
Hi Jackson, thank you very much for your reply.

Well, I will have to check it in detail, however in my rulechains I usually have a few script nodes which I name "NOP" (no operation), which I use as a convenience while debugging the rule chain (particularly when I need to view debug output from multiple preceding node paths). 

Such nodes implement the "return {msg: msg, metadata: metadata, msgType: msgType};" script and unfortunately I have had the problem also occur on these nodes.

So i think this would not apply to your use case example.

**Comment by JacksonBowe** [comment] 2021-09-01 22:23
Ah that is unfortunate. I also do the same with Blue script nodes to add debug checkpoints.

When you encounter one of these problem nodes, are you able to reproduce the error in the testing screen? You mentioned it resolves when you resave the chain, but what about before then?

**Comment by gabrielpanasco** [comment] 2021-09-02 13:09
While the node is stuck we once opened the test screen to debug the code and it worked. So it seemed that, at least using the test screen the node was funcional.

**Comment by vvlladd28** [comment] 2021-09-02 13:11
Hi @JacksonBowe,
This issue has been fixed in TB 3.3.0.

**Comment by gabrielpanasco** [comment] 2021-09-02 13:23
Hi Vladyslav, thank you very much for this information. I will try upgrading to 3.3.0.

**Closed** 2021-09-02 14:03 UTC
Labels: bug
