### ISSUE TITLE
Running on RPi3 and sometimes cannot start up correctly.

### ISSUE THREAD

**Issue by zenz** [thingsboard/thingsboard#54] opened 2017-02-16 06:07 UTC
when check with the thingsboard.out file, I found this:
Java HotSpot(TM) Client VM warning: You have loaded library /tmp/libnetty-transport-native-epoll3366333240533337390.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

how to fix this problem?

**Comment by volodymyr-babak** [comment] 2017-02-16 11:05
@zenz first let me clarify please couple questions:
1. have you reduced memory usage for both Thingsboard and Cassandra services according to setup documentation for RPi3 https://thingsboard.io/docs/user-guide/install/rpi/?
2. by saying "cannot start up correctly" you mean that Thingsboard service as process is not running OR process is running but you are not able to open UI? 
3. could you please attach to issue entire thingsboard.out and thingsboard.log files?

**Comment by zenz** [comment] 2017-02-17 11:03
1. I already modify the memory usage as the document saids
2. two states, sometimes thingsboard service is running, but cannot open UI, sometimes even not running as I check with the service --status-all cmd.


[thingsboard.log.txt](https://github.com/thingsboard/thingsboard/files/783009/thingsboard.log.txt)
[thingsboard.out.txt](https://github.com/thingsboard/thingsboard/files/783010/thingsboard.out.txt)

**Comment by volodymyr-babak** [comment] 2017-02-17 11:24
@zenz 

thanks for the answers!

according to logs route cause is exception while connecting to Cassandra:

2017-02-17 18:18:46,178 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'annotationComponentDiscoveryService': Invocation of init method failed; nested exception is java.lang.NullPointerException
....
Caused by: java.lang.NullPointerException: null
at org.thingsboard.server.dao.AbstractDao.getSession(AbstractDao.java:41)
at org.thingsboard.server.dao.AbstractModelDao.findOneByStatement(AbstractModelDao.java:66)

We'll get back to you once we add fix for this kind of issues. 

Just for confirmation.
I suppose this is happening only during the startup of the RPI3. And once cassandra is up and running and you restarting Thingsboard service everything works fine?

**Comment by zenz** [comment] 2017-02-17 11:29
@volodymyr-babak may be you are right, after several reboots, I can get the thingsboard running correctly.

1. I think the JVM 1.8 not running stable on RPi3
2. Cassandra eats too much memory yet.

**Comment by ashvayka** [comment] 2017-04-14 09:43
This will be fixed when we will support PostgreSQL. Stay tuned for new release.

**Closed by ashvayka** 2017-04-14 09:43 UTC
