### ISSUE TITLE
Thingsboard dashboard widget creation time series key is not loading in the dropdown, after version upgrade 

### ISSUE THREAD

**Issue by ulaganathan11** [thingsboard/thingsboard#7496] opened 2022-10-27 02:54 UTC
OS: Ubuntu 18.04.4 LTS
 ThingsBoard: 3.4.0
 Browser: Google Chrome  107.0.5304.62
If i try to add time series key in the dashboard widget, time series keys are not loading in the dropdown. If I add manually, It gets adding and showing the in dashboard widget. It was happening after version upgrade. earlier it was working 
   
![image](https://user-images.githubusercontent.com/68693047/198178582-98fd304a-4caa-4588-9844-50eec0fd4374.png)
Times series key is not available in the dropdown.
![image](https://user-images.githubusercontent.com/68693047/198178782-7f7ea86f-c9b7-412c-9433-06dbb80c55b5.png)

API response:
![image](https://user-images.githubusercontent.com/68693047/198179064-97397fb5-18b3-406e-b789-1ca988a0d30e.png)

 
Thingsboard yml file configuration 
![image](https://user-images.githubusercontent.com/68693047/198177323-24babfb3-45a6-4481-bfde-38d72c9c88dd.png)

Thanks in advance

**Comment by Backdraft007** [comment] 2022-10-27 06:26
Please clear browser cache and try again.

**Comment by ulaganathan11** [comment] 2022-10-27 06:42
@Backdraft007 
That is not working after clearing browser cache and I also tried in incognito window.

**Comment by Backdraft007** [comment] 2022-10-27 08:42
Is it also an other widgets? Can you the widget completly new to the dashboard?

**Comment by ulaganathan11** [comment] 2022-10-27 09:07
@Backdraft007 
It is also happening to all other existing widgets and new widgets.
It was working before upgrade the version. But now it is not working in new and existing widgets.

**Comment by ashaforost** [comment] 2022-10-27 11:36
Hi @ulaganathan11 

It's a known behavior in case you set the database ts latest type to cassandra (DATABASE_TS_LATEST_TYPE). Let me know if it's the case with your instance of thingsboard

**Comment by ulaganathan11** [comment] 2022-10-27 11:49
@ashaforost 
yes.  I set the database ts latest type to cassandra

**Comment by ashaforost** [comment] 2022-10-27 13:32
Our developers stated that this issue won't be fixed, as it's not advised to set DATABASE_TS_LATEST_TYPE to Cassandra. This setting exists for backward compatibility with older thingsboard releases, and now not all code is adapted for the latest timeseries saved in cassandra.

**Comment by ulaganathan11** [comment] 2022-10-27 13:52
Hi @ashaforost,
Thank you for your reply.
Will it cause any data loss If I change the  DATABASE_TS_LATEST_TYPE  to sql now.

**Comment by ashaforost** [comment] 2024-10-03 12:17
This change will not cause any data loss. All data from the ts latest table is a duplicate of the ts table (historic). You may not see the latest timeseries on UI until new data comes in, but it's still available as historic ts.

**Closed by ashaforost** 2024-10-03 12:17 UTC
Labels: question
