### ISSUE TITLE
Digital Gauges Not Refreshing with Telemetry Data

### ISSUE THREAD

**Issue by nitinware** [thingsboard/thingsboard#856] opened 2018-06-11 03:11 UTC
I am continuously publishing temperature data to a device and I can see the temperature data visible in the device Latest Telemetry tab correctly and it is continuously updating.
When I visualize the same telemetry data on a dashboard using a digital gauge, then the telemetry data is not updating and the Digital gauge looks frozen.
I am attaching the screen shots of both Latest Telemetry tab and the dashboard containing digital gauge, the digital gauge numerical value does not change as per the telemetry data.
 
<img width="764" alt="screen shot 2018-06-10 at 10 08 47 pm" src="https://user-images.githubusercontent.com/8107038/41211128-1016ef9c-6cfb-11e8-90d3-40b45da098cf.png">
<img width="296" alt="screen shot 2018-06-10 at 10 08 59 pm" src="https://user-images.githubusercontent.com/8107038/41211129-10270fbc-6cfb-11e8-837a-9c356c9f9545.png">

Your help is highly appreciated.

Thanks,
Nitin Ware

**Comment by adityaba** [comment] 2018-06-11 10:36
@nitinware Will you please share browser logs

**Comment by nitinware** [comment] 2018-06-11 16:18
@adityaba - I am using chrome browser and I see these log statements in the browser developer console.

> angular.js:13920 You are using the ngTouch module. 
> Angular Material already has mobile click, tap, and swipe support... 
> ngTouch is not supported with Angular Material!
> (anonymous) @ angular.js:13920
> angular.js:13920 <md-backdrop> may not work properly in a scrolled, static-positioned parent container.
> (anonymous) @ angular.js:13920

**Comment by vparomskiy** [comment] 2018-06-12 09:29
Is it possible that you send value using string data type instead of numeric data type? 
For example **"38.1"** instead of **38.1**

**Comment by nitinware** [comment] 2018-06-12 15:17
@vparomskiy - I am sending the temperature data as string, please check the below python script which I am using to publish telemetry to thingsboard.

Below is a sample message generated by below python script - 

> {"temperature":"30"}

```
import paho.mqtt.client as mqtt
from time import sleep
import random

broker="test.mosquitto.org"
topic_pub='v1/devices/me/telemetry'

client = mqtt.Client()

client.username_pw_set("*************")
client.connect('127.0.0.1', 1883, 1)

while True:
    x = random.randrange(30, 40)
    print(x)
    msg = '{"temperature":"'+ str(x) + '"}'
    client.publish(topic_pub, msg)
    sleep(0.1)
```

**Comment by nitinware** [comment] 2018-06-13 03:34
I would like to add more information that the Digital Gauge is frozen and not refreshing when it is non-edit mode on dashboard, but when I try to edit the digital gauge then I can see the Digital Gauge values changing background of edit window. I am attaching the gify screen shot of the same.

![digital_gauge_edit](https://user-images.githubusercontent.com/8107038/41328984-9af7690c-6e90-11e8-8846-708942c23076.gif)

**Comment by vparomskiy** [comment] 2018-06-13 07:39
Thank you for details.  You are right, it is a bug in a gauges widget. Updates are visible in this widget, but value not updated properly. 
In other widgets, for example in 'charts', it works as expected.

We will fix this.

**Comment by Neuromystix** [comment] 2018-06-19 12:17
@vparomskiy Hi. I'm having exactly the same problem with a timeseries flot. When i open the dashboard, the values are refreshed, but stay frozen at that values. And don't refresh with the new ones when i'm in edit mode. Tried in Chromium (RPI) and Firefox, but the problem is the same. To get the new ones, i need to refresh the page or change timewindow value to a different one and update. Same log in develoer console as @nitinware have:
"You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!
<md-backdrop> may not work properly in a scrolled, static-positioned parent container."

**Comment by vparomskiy** [comment] 2018-06-19 12:36
This issue already resolved in master, but not released yet.
As a workaround, you can decrease data submission rate. It is reproduced only when submission rate is higher than 1 per 2 seconds.

**Comment by Neuromystix** [comment] 2018-06-19 14:14
Ok, i'll wait for the master, not a big deal right now ;)
My submission rate is 20 seconds, so it shouldn't happen. Checked with a timeseries table, also happening.

**Comment by vparomskiy** [comment] 2018-06-20 12:05
@Neuromystix also could you write what time window is configured for time series flot. Is it **realtime** or **history**?

**Comment by Neuromystix** [comment] 2018-06-20 14:58
All widgets was using "dashboard timewindow", with "realtime". Didn't tried to check history. It was a fresh 2.0.3 install, running in a RPi3 which received data from a sensor, each 20 seconds. It was working fine with an old 1.4 version (had some problems with RPi SD card, so i've done a clean install).

**Comment by vparomskiy** [comment] 2019-02-05 22:01
Fix already available. Closing this issue.

**Closed by vparomskiy** 2019-02-05 22:02 UTC
Labels: bug

**Comment by bachrc** [comment] 2019-02-18 14:00
Nope, I still have the issue in the latest release of Thingsboard : 2.3.0. I am using the docker image tb-postgres.

**Comment by lepgithub** [comment] 2019-03-31 03:31
@vparomskiy @bachrc 
I can also confirm the digital gauge widgets are not refreshing properly however the analog widgets are correct. The graphical part of the digital gauge appears to update correctly, just the numerical value does not. Also all widgets refresh correctly if I reload the web page or while in edit mode. Dashboard is set to realtime at 1 sec and data is sent at once a sec via mqtt. I'm using docker v2.3.0 tb-postgres.

**Comment by amirNoob89** [comment] 2019-04-05 04:08
is the issue already solved? having the same problem. Where can get the latest solution for this issue? thank you.

**Comment by bachrc** [comment] 2019-04-06 17:02
I hope a patch will be available in the 2.4.0, because it is really annoying.

**Comment by adambforbes** [comment] 2019-05-03 23:51
I'm still having this with digital widget refreshing too. Some of my digital widgets refresh and others do not. Data uploads are every 10 minutes.

**Comment by lepgithub** [comment] 2019-05-04 00:07
@adambforbes Try disabling animation under Edit Widget Advance. It worked for me, value is now accurate.

**Comment by adambforbes** [comment] 2019-05-04 00:29
That seemed to fix it. Thank you!

**Comment by ecmap** [comment] 2020-04-25 13:35
I still have the issue.....

**Comment by goboras** [comment] 2020-05-12 10:20
tb-postgress docker ver. 2.4.3 same issue
