### ISSUE TITLE
Value rendering issues on mobile devices

### ISSUE THREAD

**Issue by abhishekanne** [thingsboard/thingsboard#1226] opened 2018-11-05 16:26 UTC
We recently migrated our dashboard from TB1.4 to TB 2.1.3

Its working fine on desktop web view.

On mobile browsers ,latest  Chrome and FF we observe that values on digital mini guages and  trending graphs not visible after dashboard load. If we change the screen mode from portrait to landscape or vise versa values appears.

This was not an issue with 1.4. 

As we already migrated to latest version and there are major changes  in rule engine downgrading to older version cant be easy option.

**Comment by Rworld-Ravi** [comment] 2020-05-21 13:53
as referenced here : [https://github.com/thingsboard/thingsboard/issues/856](url) ,  if you disable the animation for that widget the values render fine. Although the bug is said to be resolved in TB2.5 as mentioned here: [https://github.com/thingsboard/thingsboard/issues/2669#issuecomment-628554280](url) , the issue is still there.  Disabling animation seems to be the only work around.

**Comment by Ultrazombie** [comment] 2023-06-20 08:39
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Closed by Ultrazombie** 2023-06-20 08:39 UTC
