### ISSUE TITLE
[Bug] starting via systemd fails

### ISSUE THREAD

**Issue by keestux** [thingsboard/thingsboard#5681] opened 2021-12-04 18:26 UTC
**Describe the bug**
Thingsboard does not start properly via the systemd configuration.

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.3.2-1 (downloaded from the github releases)
  * Ubuntu 20.04

**To Reproduce**
* restart the system
It's as simple as this.

Although the thingsboard process was started, it failed after a short while with an error.
```
Dec  4 13:39:07 test systemd[1]: Started thingsboard.
...
Dec  4 13:40:30 test systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Dec  4 13:40:30 test systemd[1]: thingsboard.service: Failed with result 'exit-code'.
```

In the thingsboard.log there is this error
```
2021-12-04 13:40:25,306 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:311)
	at org.thingsboard.server.transport.snmp.service.ProtoTransportEntityService.getSnmpDevicesIds(ProtoTransportEntityService.java:89)
	at org.thingsboard.server.transport.snmp.SnmpTransportContext.fetchDevicesAndEstablishSessions(SnmpTransportContext.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:308)
	... 28 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.setTimeoutException(DefaultTbQueueRequestTemplate.java:163)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$tryCleanStaleRequests$0(DefaultTbQueueRequestTemplate.java:132)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.tryCleanStaleRequests(DefaultTbQueueRequestTemplate.java:128)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:117)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
**Expected behavior**
Thingsboard should start normally.

**Additional context**
I've tried to add a line to the systemd configuration, but that didn't help.
```
[Unit]
Description=thingsboard
After=syslog.target
Requires=kafka.service
```

**Comment by keestux** [comment] 2022-01-30 13:59
Hey @ashaforost, the log file is quite large, 93011 lines long. I'm assuming it is too large to attach in this issue. No?

**Comment by ashaforost** [comment] 2022-01-31 09:01
Hi @keestux 
In case your log file is bigger than 25Mb, try compressing it and sending me a .zip file, I believe there mustn't be any issues.

**Comment by keestux** [comment] 2022-01-31 19:06
OK here is a log file from three days ago, when we had to restart the server.
[thingsboard.2022-01-28.0.log](https://github.com/thingsboard/thingsboard/files/7973461/thingsboard.2022-01-28.0.log)

**Comment by ashaforost** [comment] 2022-02-03 09:43
Hi @keestux ,

I see that you've upgraded to v3.3.3, and with the upgrade to v3.3.3, a new bug appeared with our SNMP protocol, due to which the application occasionally fails. 
Please disable SNMP by adding the next line to the thingsboard.conf file and restart the service:
export SNMP_ENABLED=false

**Comment by Ultrazombie** [comment] 2022-02-08 20:37
Hello @keestux ,
was closed because the last comment should help you with this problem and you haven't responded to anything in 5 days. Please confirm that this helped your problem.
We are aware of this bug and our programmers are doing their best to fix it
If you want we will leave this ticket open until the problem is solved?

**Comment by keestux** [comment] 2022-02-08 21:45
> We are aware of this bug and our programmers are doing their best to fix it

Are you talking about the systemd bug? Or about the SNMP bug?

**Comment by Ultrazombie** [comment] 2022-05-27 07:53
Hello,
The SNMP bug has been resolved in the latest versions of ThingsBoard.

**Closed by Ultrazombie** 2022-05-27 07:53 UTC
Labels: bug
