### ISSUE TITLE
[Question] Compare new vs existing attribute value via Rule Chain

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3384] opened 2020-08-28 15:50 UTC
Hi All,
Is there a way to pull existing attribute values from device and compare it with new one arriving from the message via rule engine ?
I am able to check for fields and do whatever i want with them upon arrival and new messages - but is there a way to pull exisitng attribute value from the device ?

What i`m trying to achieve is minimise the number of  communication attempts between server and device.
I store some value as shared attribute, when i change it one the device i want to compare it on entry with existing one on the server first before it gets recorded, since once recorder it will be a change and will send the same message back to the device and this is what i`m trying to avoid.

**Comment by ChantsovaEkaterina** [comment] 2020-08-31 09:14
Hi,
You can use the _Originator Attributes_ rule node for pulling existing attributes.

**Comment by amizer12** [comment] 2020-08-31 17:04
Perfect !
Basedon your suggestion i added existing values to metadata, apss to the script node in which i compare them and decide on what to do with them based on result.
Many thanks for your help !

**Comment by fjpanag** [comment] 2020-09-01 20:16
@amizer12 Your issue is related to #1809.

Unfortunately, what you describe **will not work correctly** in practice! I tried a very similar thing, causing unimaginable frustration.

0. Device has value 'A'.
1. You change the attribute value to 'B'.
2. Quickly enough you change again the attribute value to 'C'.
3. Due to network latency, you get the response for (1), and proceed to save it since there is a change in value (A -> B).
4. Due to saving in (3), you send again the value 'B'.
5. Response from (2) arrives now. Since there was a change in value (A -> C), you save it.
6. Due to saving in (5), you send again the value 'C'.
7. Response from (4) arrives now. Since there was a change in value (C -> B), you save it.
8. Due to saving in (7), you send again the value 'B'.
9. Response from (6) arrives now. Since there was a change in value (B -> C), you save it.
10. Due to saving in (9), you send again the value 'C'.

And this continues to infinity... We triggered this very often in our application (app 20% of the time), and causes the attribute value to flicker back and forth between the two values.

I believe that the only proper remedy to this, is to actually control whether the new value should be sent to the device or not.

**Comment by amizer12** [comment] 2020-09-02 12:56
@fjpanag 
Agree - just tested this couple times and almost blown my relays due to multiple updates back and forth.
I`ll test it now with the approach of checking locally on device new data once it arrives form the TB whenever they are different the the ones i have locally if so - i`ll allow update, if not - i`ll do nothing.

**Comment by fjpanag** [comment] 2020-09-07 18:26
@amizer12 My device *does* check whether the received attributes are different than the existing.

The above problematic sequence will also appear if you do this check. Checking whether the attributes are different will not solve the issue. It will just hide it, till attributes are updated with the right timing.

**Comment by amizer12** [comment] 2020-09-07 21:30
@fjpanag so checking if value need to be changed (based on your suggestion above) is not fixing the issue and i do agree.
I'm thinking on putting some counter or timer that will somehow prevent values going up and down if the timing will cause the problem again.
Have you been able to solve the issue at your end?

**Comment by fjpanag** [comment] 2020-09-08 17:23
@amizer12 Yes I did just this. I implemented a time-based "filter".
When a new attribute arrives, the device waits some seconds till it publishes its values. The idea is that all pending messages will have arrived by then, so only the latest value will be sent back.

Keep in mind that the delay must be somehow more than your MQTT timeout value.

Of course, it is not working too. **It is horrible**.
It somehow makes things better, that's way I have left this in. It mostly solves problems caused by #1810. And generally the system, if it gets to the point of oscillating, it will eventually stop.

But:
1. The problem is not solved. With the right timing you will have oscillations again. (caused if the second command arrives just by the time the filter has timed-out).
2. The device response is now very very slow. You have to wait for the filter to expire to get the new value in the dashboard.
3. Initialization of our system is a mess...
4. Network traffic can be seriously reduced.

@vvlladd28 Please reopen the issue. It is not resolved.

**Comment by ashvayka** [comment] 2020-09-14 08:41
Hi @fjpanag and @amizer12. I am sorry for your bad experience. 

First, there is actually an issue, see my comment:  https://github.com/thingsboard/thingsboard/issues/1809#issuecomment-691902725 and we will fix it asap, in the next release (2.5.5 and 3.1.2). @YevhenBondarenko will put a comment/close the issue once this released.

Second, we have not noticed the issue for a while, because we were not expecting anyone to push the same attribute from both device and server. The original idea of the client/shared attribute is the following:
1) The client reports its current state as the client-side attribute and subscribes to the changes of a shared attribute. For example, currentSetting and targetSetting.
2) The user may change the desired state as a shared attribute. For example, targetSetting. Client will receive it and report the currentSetting as a client-side attribute.
In such a case, you, as a user, always know what is the latest state of the device and the latest state of the configuration. On the dashboard, you can show device status "in sync" and "out of sync" by comparing those two attributes. I believe this is much better approach, please let me know if this does not work for you. We would also appreciate more details about your use case if the suggested approach does not work.

**Comment by amizer12** [comment] 2020-09-14 09:55
Thanks so much for the  input.
I`m using multiple attributes to control the device.
I think that initially in TB architecture this use case is addressed via
RPC functionality. I`m using attributes so i can store the latest value and
also push them all at once once device is offline/online.
Based on your explanation i think the better design for my case would be to
have attributes to read the state of the device switches ec. BUT from TB
into the device only use RPC commands to enable/disable switches and relays.
So in that case i will separate the read and write operation and use only
attributes for reading and writing only via RPC - does that make sense ?

pon., 14 wrz 2020 o 10:42 Andrew Shvayka <notifications@github.com>
napisał(a):

**Comment by ashvayka** [comment] 2020-09-15 07:25
If I understood you correctly, you will write a shared attribute from UI (REST API), but the device will not [subscribe](https://thingsboard.io/docs/reference/mqtt-api/#subscribe-to-attribute-updates-from-the-server) to it. Instead of subscribe, you will send an [RPC](https://thingsboard.io/docs/reference/mqtt-api/#server-side-rpc) call and device will 
[request](https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server) the latest attribute values from server? You will also [request](https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server) the latest attribute values on device boot, right?

**Comment by amizer12** [comment] 2020-09-15 09:14
HI Andrew - yes, that is correct - i will try that approach and see if it
works better than the one i have now purely relying on attributes.

wt., 15 wrz 2020 o 09:25 Andrew Shvayka <notifications@github.com>
napisał(a):

**Comment by fotis400** [comment] 2020-09-16 20:51
Hi @ashvayka, 
Unfortunately your proposition is not going to work correctly, at least in my use case.

The user sees a value on a widget, and edits it. The device is notified about the new value that the user selected.
However, when you change a value you actually need to know what is the currently set one.

In your scenario, the widget will use the shared attribute, and thus it will initially show the last set value. Not the currently active. This will create great confusion to the users!

For this reason I copy the device attributes to the shared ones. Thus the widgets show the currently active value, and can also accept a new value to send to the device.

**Comment by YevhenBondarenko** [comment] 2020-09-18 10:32
#3487

**Closed** 2022-06-14 07:50 UTC
Labels: question
